// TS-ONLY: cross-language bincode fixture validation
//
// These tests read binary fixture files generated by the Rust side
// (ankurah-ts-support/proto/tests/bincode_fixtures.rs) and validate
// that the TypeScript bincode codec produces identical results.
//
// For each fixture we do TWO checks:
//   1. Decode the .bin file and verify field values (Rust -> TS decode).
//   2. Construct matching TS values, encode them, and compare bytes (TS encode -> Rust).
//
// NOTE: The fixtures were generated from the ts-port-support branch, which predates
// the addition of SubscribeEntity/EntitiesSubscribed/UnsubscribeEntities variants.
// The variant numbering for NodeRequestBody and NodeResponseBody in the fixtures
// does NOT match the current TS class decode. Where this matters, we manually
// decode/encode using raw reader/writer calls with the fixture's variant numbers.

import { describe, test, expect, beforeAll } from 'bun:test';
import { readFileSync, existsSync } from 'fs';
import path from 'path';

import {
  BincodeReader,
  BincodeWriter,
  EntityId,
  EventId,
  TransactionId,
  RequestId,
  QueryId,
  UpdateId,
  CollectionId,
  Clock,
  AuthData,
  Attestation,
  AttestationSet,
  Attested,
  Operation,
  OperationSet,
  StateBuffers,
  State,
  EntityState,
  Event,
  EventFragment,
  StateFragment,
  NodeRequest,
  NodeResponse,
  NodeUpdate,
  NodeUpdateAck,
  NodeUpdateBody,
  NodeUpdateAckBody,
  UpdateContent,
  MembershipChange,
  SubscriptionUpdateItem,
  Presence,
  CausalRelation,
  CausalAssertion,
  CausalAssertionFragment,
  DeltaContent,
  EntityDelta,
  KnownEntity,
  NodeRequestBody,
  NodeResponseBody,
  Message,
  NodeMessage,
} from '../src/index';

import { Item } from '../src/sys';

import { ulidStringToBytes } from '../src/id.provided';

// ── Fixture path resolution ─────────────────────────────────────────────────

const FIXTURE_DIR = path.resolve(__dirname, '../../../../ankurah-ts-support/proto/test_fixtures');

function loadFixture(name: string): Uint8Array {
  const filePath = path.join(FIXTURE_DIR, name);
  if (!existsSync(filePath)) {
    throw new Error(
      `Fixture file not found at ${filePath}. ` +
      `Ensure the ankurah-ts-support worktree exists at ../ankurah-ts-support ` +
      `with the ts-port-support branch checked out.`
    );
  }
  const buf = readFileSync(filePath);
  return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
}

// ── Deterministic value constructors (mirrors Rust helpers) ──────────────────

function makeEntityId(seed: number): EntityId {
  const bytes = new Uint8Array(16);
  for (let i = 0; i < 16; i++) {
    bytes[i] = (seed + i) & 0xff;
  }
  return EntityId.fromBytes(bytes);
}

function makeEventId(seed: number): EventId {
  const bytes = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    bytes[i] = (seed + i) & 0xff;
  }
  return EventId.fromBytes(bytes);
}

/**
 * Construct a ULID-based ID from a seed, matching the Rust pattern:
 *   format!("0000000000000000000000{:04}", seed)
 * which produces a 26-char Crockford Base32 string with the seed as decimal digits.
 * e.g. seed=0x10 (16) -> "00000000000000000000000016"
 *      seed=0x30 (48) -> "00000000000000000000000048"
 */
function makeUlidBytes(seed: number): Uint8Array {
  // Rust format!("{:04}", seed) uses decimal formatting
  const seedStr = seed.toString(10).padStart(4, '0');
  const ulidStr = '0000000000000000000000' + seedStr;
  return ulidStringToBytes(ulidStr);
}

function makeTransactionId(seed: number): TransactionId {
  return TransactionId.fromBytes(makeUlidBytes(seed));
}

function makeRequestId(seed: number): RequestId {
  return RequestId.fromBytes(makeUlidBytes(seed));
}

function makeUpdateId(seed: number): UpdateId {
  return UpdateId.fromBytes(makeUlidBytes(seed));
}

function makeQueryId(id: number): QueryId {
  return QueryId.test(BigInt(id));
}

function makeCollectionId(name: string): CollectionId {
  return CollectionId.from(name);
}

function makeClockEmpty(): Clock {
  return Clock.new([]);
}

function makeClockSingle(): Clock {
  return Clock.new([makeEventId(0x10)]);
}

function makeClockMulti(): Clock {
  return Clock.new([
    makeEventId(0x10),
    makeEventId(0x30),
    makeEventId(0x50),
  ]);
}

function makeOperation(diff: number[]): Operation {
  return new Operation(new Uint8Array(diff));
}

function makeOperationSet(): OperationSet {
  const map = new Map<string, Operation[]>();
  map.set('backend_a', [
    makeOperation([0xAA, 0xBB]),
    makeOperation([0xCC]),
  ]);
  map.set('backend_b', [
    makeOperation([0xDD, 0xEE, 0xFF]),
  ]);
  return new OperationSet(map);
}

function makeStateBuffers(): StateBuffers {
  const map = new Map<string, Uint8Array>();
  map.set('buf_alpha', new Uint8Array([0x01, 0x02, 0x03]));
  map.set('buf_beta', new Uint8Array([0x04, 0x05]));
  return new StateBuffers(map);
}

function makeState(): State {
  return new State(makeStateBuffers(), makeClockSingle());
}

function makeAttestation(bytes: number[]): Attestation {
  return new Attestation(new Uint8Array(bytes));
}

function makeAttestationSetEmpty(): AttestationSet {
  return new AttestationSet([]);
}

function makeAttestationSetTwo(): AttestationSet {
  return new AttestationSet([
    makeAttestation([0x42, 0x43]),
    makeAttestation([0x44, 0x45, 0x46]),
  ]);
}

function makeStateFragment(): StateFragment {
  return new StateFragment(makeState(), makeAttestationSetTwo());
}

function makeEventFragment(): EventFragment {
  return new EventFragment(
    makeOperationSet(),
    makeClockSingle(),
    makeAttestationSetEmpty(),
  );
}

function makeEntityState(): EntityState {
  return new EntityState(
    makeEntityId(0x00),
    makeCollectionId('test_collection'),
    makeState(),
  );
}

function makeEvent(): Event {
  return new Event(
    makeCollectionId('test_collection'),
    makeEntityId(0x00),
    makeOperationSet(),
    makeClockSingle(),
  );
}

function makeKnownEntity(): KnownEntity {
  return new KnownEntity(makeEntityId(0x20), makeClockSingle());
}

function makeCausalAssertionFragment(): CausalAssertionFragment {
  return new CausalAssertionFragment(
    new CausalRelation('Equal', {}),
    makeAttestationSetTwo(),
  );
}

/**
 * Encode a Selection { predicate: name = 'test', order_by: None, limit: None }
 * in bincode format, matching the Rust make_selection() helper.
 *
 * Layout:
 *   Predicate::Comparison (variant 0)
 *     left: Expr::Path (variant 1)
 *       PathExpr { steps: ["name"] }
 *     operator: ComparisonOperator::Equal (variant 0)
 *     right: Expr::Literal (variant 0)
 *       Literal::String (variant 5) "test"
 *   order_by: None (0u8)
 *   limit: None (0u8)
 */
function encodeSelection(writer: BincodeWriter): void {
  // Predicate::Comparison = variant 0
  writer.writeVariant(0);
  // left: Expr::Path = variant 1
  writer.writeVariant(1);
  // PathExpr { steps: Vec<String> }
  writer.writeLength(1); // vec len = 1
  writer.writeString('name'); // steps[0]
  // operator: ComparisonOperator::Equal = variant 0
  writer.writeVariant(0);
  // right: Expr::Literal = variant 0
  writer.writeVariant(0);
  // Literal::String = variant 5
  writer.writeVariant(5);
  writer.writeString('test');
  // order_by: Option::None
  writer.writeU8(0);
  // limit: Option::None
  writer.writeU8(0);
}

/**
 * Read past a Selection in the reader (skip the known bytes).
 * Returns the raw bytes consumed for verification.
 */
function skipSelection(reader: BincodeReader): void {
  // Predicate variant
  const predVariant = reader.readVariant();
  expect(predVariant).toBe(0); // Comparison
  // left: Expr variant
  const leftVariant = reader.readVariant();
  expect(leftVariant).toBe(1); // Path
  // PathExpr steps
  const stepsLen = reader.readLength();
  expect(stepsLen).toBe(1);
  const step0 = reader.readString();
  expect(step0).toBe('name');
  // operator
  const opVariant = reader.readVariant();
  expect(opVariant).toBe(0); // Equal
  // right: Expr variant
  const rightVariant = reader.readVariant();
  expect(rightVariant).toBe(0); // Literal
  // Literal::String variant
  const litVariant = reader.readVariant();
  expect(litVariant).toBe(5); // String
  const litStr = reader.readString();
  expect(litStr).toBe('test');
  // order_by: None
  const orderBy = reader.readU8();
  expect(orderBy).toBe(0);
  // limit: None
  const limit = reader.readU8();
  expect(limit).toBe(0);
}

// ── Helper: compare encoded bytes to fixture ─────────────────────────────────

function expectBytesEqual(actual: Uint8Array, expected: Uint8Array, label: string): void {
  if (actual.length !== expected.length) {
    // Find first difference for debugging
    const minLen = Math.min(actual.length, expected.length);
    for (let i = 0; i < minLen; i++) {
      if (actual[i] !== expected[i]) {
        throw new Error(
          `${label}: length mismatch (actual ${actual.length} vs expected ${expected.length}), ` +
          `first difference at byte ${i}: actual 0x${actual[i].toString(16).padStart(2, '0')} ` +
          `vs expected 0x${expected[i].toString(16).padStart(2, '0')}`
        );
      }
    }
    throw new Error(`${label}: length mismatch (actual ${actual.length} vs expected ${expected.length})`);
  }
  for (let i = 0; i < actual.length; i++) {
    if (actual[i] !== expected[i]) {
      throw new Error(
        `${label}: mismatch at byte ${i}: actual 0x${actual[i].toString(16).padStart(2, '0')} ` +
        `vs expected 0x${expected[i].toString(16).padStart(2, '0')}`
      );
    }
  }
}

// ── Fixture variant numbering note ───────────────────────────────────────────
// The fixtures were generated from ts-port-support (pre SubscribeEntity/EntitiesSubscribed).
// Fixture NodeRequestBody variants: CommitTransaction=0, Get=1, GetEvents=2, Fetch=3, SubscribeQuery=4
// Fixture NodeResponseBody variants: CommitComplete=0, Fetch=1, Get=2, GetEvents=3, QuerySubscribed=4, Success=5, Error=6
// Current TS class variants differ (SubscribeEntity=2 shifts request; EntitiesSubscribed=3 shifts response).
// Where class decode/encode is used for these bodies, we use manual raw decode/encode instead.

// ── Test: verify fixture directory exists ────────────────────────────────────

beforeAll(() => {
  if (!existsSync(FIXTURE_DIR)) {
    throw new Error(
      `Fixture directory not found at ${FIXTURE_DIR}. ` +
      `Ensure the ankurah-ts-support worktree exists at ../ankurah-ts-support ` +
      `with the ts-port-support branch checked out.`
    );
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// IDS FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('ids.bin fixture', () => {
  test('decode: EntityId, EventId, TransactionId, RequestId, QueryId, UpdateId, CollectionId', () => {
    const data = loadFixture('ids.bin');
    const reader = new BincodeReader(data);

    // EntityId: bytes [0,1,2,...,15]
    using entityId = EntityId.decode(reader);
    expect(entityId.bytes).toEqual(new Uint8Array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]));

    // EventId: bytes [0,1,2,...,31]
    using eventId = EventId.decode(reader);
    expect(eventId.bytes).toEqual(new Uint8Array([
      0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
      16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
    ]));

    // TransactionId: ULID string "00000000000000000000000016" (seed=0x10=16)
    using transactionId = TransactionId.decode(reader);
    expect(transactionId.toUlidString()).toBe('00000000000000000000000016');

    // RequestId: ULID string "00000000000000000000000032" (seed=0x20=32)
    using requestId = RequestId.decode(reader);
    expect(requestId.toUlidString()).toBe('00000000000000000000000032');

    // QueryId: test(42) = Ulid::from_parts(42, 0)
    using queryId = QueryId.decode(reader);
    { using expected = QueryId.test(42n); expect(queryId.toUlidString()).toBe(expected.toUlidString()); }

    // UpdateId: ULID string "00000000000000000000000048" (seed=0x30=48)
    using updateId = UpdateId.decode(reader);
    expect(updateId.toUlidString()).toBe('00000000000000000000000048');

    // CollectionId: "test_collection"
    using collectionId = CollectionId.decode(reader);
    expect(collectionId.asStr()).toBe('test_collection');

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('ids.bin');
    const writer = new BincodeWriter();

    // EntityId: bytes [0..15]
    using entityId = EntityId.fromBytes(new Uint8Array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]));
    entityId.encode(writer);

    // EventId: bytes [0..31]
    using eventId = EventId.fromBytes(new Uint8Array([
      0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
      16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
    ]));
    eventId.encode(writer);

    using transactionId = makeTransactionId(0x10);
    transactionId.encode(writer);
    using requestId = makeRequestId(0x20);
    requestId.encode(writer);
    using queryId = makeQueryId(42);
    queryId.encode(writer);
    using updateId = makeUpdateId(0x30);
    updateId.encode(writer);
    using collectionId = makeCollectionId('test_collection');
    collectionId.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'ids.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// CLOCK FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('clock.bin fixture', () => {
  test('decode: empty, single, multi clocks', () => {
    const data = loadFixture('clock.bin');
    const reader = new BincodeReader(data);

    using empty = Clock.decode(reader);
    expect(empty.length).toBe(0);

    using single = Clock.decode(reader);
    expect(single.length).toBe(1);
    {
      using expected = makeEventId(0x10);
      expect(single.asSlice()[0].bytes).toEqual(expected.bytes);
    }

    using multi = Clock.decode(reader);
    expect(multi.length).toBe(3);
    {
      using e0 = makeEventId(0x10);
      using e1 = makeEventId(0x30);
      using e2 = makeEventId(0x50);
      expect(multi.asSlice()[0].bytes).toEqual(e0.bytes);
      expect(multi.asSlice()[1].bytes).toEqual(e1.bytes);
      expect(multi.asSlice()[2].bytes).toEqual(e2.bytes);
    }

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('clock.bin');
    const writer = new BincodeWriter();

    using clockEmpty = makeClockEmpty();
    clockEmpty.encode(writer);
    using clockSingle = makeClockSingle();
    clockSingle.encode(writer);
    using clockMulti = makeClockMulti();
    clockMulti.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'clock.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// AUTH FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('auth.bin fixture', () => {
  test('decode: AuthData, Attestation, AttestationSet, Attested<EntityState>', () => {
    const data = loadFixture('auth.bin');
    const reader = new BincodeReader(data);

    // AuthData with bytes
    using authDataBytes = AuthData.decode(reader);
    expect(authDataBytes._0).toEqual(new Uint8Array([0x01, 0x02, 0x03]));

    // AuthData empty
    using authDataEmpty = AuthData.decode(reader);
    expect(authDataEmpty._0).toEqual(new Uint8Array([]));

    // Attestation
    using attestation = Attestation.decode(reader);
    expect(attestation._0).toEqual(new Uint8Array([0x42, 0x43]));

    // AttestationSet empty
    using attestationSetEmpty = AttestationSet.decode(reader);
    expect(attestationSetEmpty.length).toBe(0);

    // AttestationSet with two
    using attestationSetTwo = AttestationSet.decode(reader);
    expect(attestationSetTwo.length).toBe(2);
    expect(attestationSetTwo._0[0]._0).toEqual(new Uint8Array([0x42, 0x43]));
    expect(attestationSetTwo._0[1]._0).toEqual(new Uint8Array([0x44, 0x45, 0x46]));

    // Attested<EntityState>
    using attested = Attested.decode(reader, r => EntityState.decode(r));
    { using expected = makeEntityId(0x00); expect(attested.payload.entityId.bytes).toEqual(expected.bytes); }
    expect(attested.payload.collection.asStr()).toBe('test_collection');
    expect(attested.attestations.length).toBe(2);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('auth.bin');
    const writer = new BincodeWriter();

    using authData1 = new AuthData(new Uint8Array([0x01, 0x02, 0x03]));
    authData1.encode(writer);
    using authData2 = new AuthData(new Uint8Array([]));
    authData2.encode(writer);
    using attestation = makeAttestation([0x42, 0x43]);
    attestation.encode(writer);
    using attestationSetEmpty = makeAttestationSetEmpty();
    attestationSetEmpty.encode(writer);
    using attestationSetTwo = makeAttestationSetTwo();
    attestationSetTwo.encode(writer);

    using attested = new Attested(makeEntityState(), makeAttestationSetTwo());
    attested.encode(writer, (w, es) => es.encode(w));

    expectBytesEqual(writer.finish(), fixture, 'auth.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// DATA FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('data.bin fixture', () => {
  test('decode: Operation, OperationSet, StateBuffers, State, StateFragment, Event, EventFragment, EntityState', () => {
    const data = loadFixture('data.bin');
    const reader = new BincodeReader(data);

    // Operation
    using operation = Operation.decode(reader);
    expect(operation.diff).toEqual(new Uint8Array([0xAA, 0xBB, 0xCC]));

    // OperationSet
    using operationSet = OperationSet.decode(reader);
    expect(operationSet._0.size).toBe(2);
    const backendA = operationSet.get('backend_a')!;
    expect(backendA.length).toBe(2);
    expect(backendA[0].diff).toEqual(new Uint8Array([0xAA, 0xBB]));
    expect(backendA[1].diff).toEqual(new Uint8Array([0xCC]));
    const backendB = operationSet.get('backend_b')!;
    expect(backendB.length).toBe(1);
    expect(backendB[0].diff).toEqual(new Uint8Array([0xDD, 0xEE, 0xFF]));

    // StateBuffers
    using stateBuffers = StateBuffers.decode(reader);
    expect(stateBuffers._0.size).toBe(2);
    expect(stateBuffers.get('buf_alpha')).toEqual(new Uint8Array([0x01, 0x02, 0x03]));
    expect(stateBuffers.get('buf_beta')).toEqual(new Uint8Array([0x04, 0x05]));

    // State
    using state = State.decode(reader);
    expect(state.stateBuffers._0.size).toBe(2);
    expect(state.head.length).toBe(1);

    // StateFragment
    using stateFragment = StateFragment.decode(reader);
    expect(stateFragment.state.stateBuffers._0.size).toBe(2);
    expect(stateFragment.attestations.length).toBe(2);

    // Event
    using event = Event.decode(reader);
    expect(event.collection.asStr()).toBe('test_collection');
    { using expected = makeEntityId(0x00); expect(event.entityId.bytes).toEqual(expected.bytes); }
    expect(event.operations._0.size).toBe(2);
    expect(event.parent.length).toBe(1);

    // EventFragment
    using eventFragment = EventFragment.decode(reader);
    expect(eventFragment.operations._0.size).toBe(2);
    expect(eventFragment.parent.length).toBe(1);
    expect(eventFragment.attestations.length).toBe(0);

    // EntityState
    using entityState = EntityState.decode(reader);
    { using expected = makeEntityId(0x00); expect(entityState.entityId.bytes).toEqual(expected.bytes); }
    expect(entityState.collection.asStr()).toBe('test_collection');
    expect(entityState.state.head.length).toBe(1);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('data.bin');
    const writer = new BincodeWriter();

    using operation = makeOperation([0xAA, 0xBB, 0xCC]);
    operation.encode(writer);
    using operationSet = makeOperationSet();
    operationSet.encode(writer);
    using stateBuffers = makeStateBuffers();
    stateBuffers.encode(writer);
    using state = makeState();
    state.encode(writer);
    using stateFragment = makeStateFragment();
    stateFragment.encode(writer);
    using event = makeEvent();
    event.encode(writer);
    using eventFragment = makeEventFragment();
    eventFragment.encode(writer);
    using entityState = makeEntityState();
    entityState.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'data.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// REQUEST FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════
// Fixture variant numbering (pre-SubscribeEntity):
//   CommitTransaction=0, Get=1, GetEvents=2, Fetch=3, SubscribeQuery=4
// Current TS class numbering (post-SubscribeEntity):
//   CommitTransaction=0, Get=1, SubscribeEntity=2, GetEvents=3, Fetch=4, SubscribeQuery=5
// The first NodeRequest has body=Get (variant 1, same in both) so class decode works.
// Standalone body entries are decoded manually with fixture variant numbers.

describe('request.bin fixture', () => {
  test('decode: NodeRequest, CommitTransaction, Get, GetEvents, Fetch, SubscribeQuery', () => {
    const data = loadFixture('request.bin');
    const reader = new BincodeReader(data);

    // NodeRequest (Get variant) — variant 1 = Get in both fixture and TS
    using nodeRequest = NodeRequest.decode(reader);
    { using expected = makeRequestId(0x01); expect(nodeRequest.id.toUlidString()).toBe(expected.toUlidString()); }
    { using expected = makeEntityId(0x10); expect(nodeRequest.to.bytes).toEqual(expected.bytes); }
    { using expected = makeEntityId(0x20); expect(nodeRequest.from.bytes).toEqual(expected.bytes); }
    expect(nodeRequest.body.type).toBe('Get');
    if (nodeRequest.body.is('Get')) {
      expect(nodeRequest.body.value.collection.asStr()).toBe('users');
      expect(nodeRequest.body.value.ids.length).toBe(1);
      { using expected = makeEntityId(0x30); expect(nodeRequest.body.value.ids[0].bytes).toEqual(expected.bytes); }
    }

    // CommitTransaction body (standalone) — fixture variant 0
    const commitVariant = reader.readVariant();
    expect(commitVariant).toBe(0); // CommitTransaction
    using commitTxId = TransactionId.decode(reader);
    { using expected = makeTransactionId(0x01); expect(commitTxId.toUlidString()).toBe(expected.toUlidString()); }
    const commitEvents = reader.readVec(r => Attested.decode(r, r2 => Event.decode(r2)));
    expect(commitEvents.length).toBe(1);
    expect(commitEvents[0].attestations.length).toBe(0);
    for (const e of commitEvents) e.drop();

    // Get body (standalone) — fixture variant 1
    const getVariant = reader.readVariant();
    expect(getVariant).toBe(1); // Get
    using getCollection = CollectionId.decode(reader);
    expect(getCollection.asStr()).toBe('users');
    const getIds = reader.readVec(r => EntityId.decode(r));
    expect(getIds.length).toBe(2);
    { using expected = makeEntityId(0x40); expect(getIds[0].bytes).toEqual(expected.bytes); }
    { using expected = makeEntityId(0x50); expect(getIds[1].bytes).toEqual(expected.bytes); }
    for (const id of getIds) id.drop();

    // GetEvents body (standalone) — fixture variant 2 (TS class: 3)
    const getEventsVariant = reader.readVariant();
    expect(getEventsVariant).toBe(2); // GetEvents in fixture
    using getEventsCollection = CollectionId.decode(reader);
    expect(getEventsCollection.asStr()).toBe('users');
    const getEventsIds = reader.readVec(r => EventId.decode(r));
    expect(getEventsIds.length).toBe(1);
    { using expected = makeEventId(0x60); expect(getEventsIds[0].bytes).toEqual(expected.bytes); }
    for (const id of getEventsIds) id.drop();

    // Fetch body (standalone) — fixture variant 3 (TS class: 4)
    const fetchVariant = reader.readVariant();
    expect(fetchVariant).toBe(3); // Fetch in fixture
    using fetchCollection = CollectionId.decode(reader);
    expect(fetchCollection.asStr()).toBe('users');
    // Skip selection (verified inline)
    skipSelection(reader);
    const fetchKnown = reader.readVec(r => KnownEntity.decode(r));
    expect(fetchKnown.length).toBe(1);
    { using expected = makeEntityId(0x20); expect(fetchKnown[0].entityId.bytes).toEqual(expected.bytes); }
    for (const ke of fetchKnown) ke.drop();

    // SubscribeQuery body (standalone) — fixture variant 4 (TS class: 5)
    const subVariant = reader.readVariant();
    expect(subVariant).toBe(4); // SubscribeQuery in fixture
    using subQueryId = QueryId.decode(reader);
    { using expected = makeQueryId(99); expect(subQueryId.toUlidString()).toBe(expected.toUlidString()); }
    using subCollection = CollectionId.decode(reader);
    expect(subCollection.asStr()).toBe('users');
    skipSelection(reader);
    const subVersion = reader.readU32();
    expect(subVersion).toBe(1);
    const subKnown = reader.readVec(r => KnownEntity.decode(r));
    expect(subKnown.length).toBe(0);
    for (const ke of subKnown) ke.drop();

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('request.bin');
    const writer = new BincodeWriter();

    // NodeRequest (full struct with Get body) — variant 1 = Get in both
    using nodeRequest = new NodeRequest(
      makeRequestId(0x01),
      makeEntityId(0x10),
      makeEntityId(0x20),
      new NodeRequestBody('Get', { collection: makeCollectionId('users'), ids: [makeEntityId(0x30)] }),
    );
    nodeRequest.encode(writer);

    // CommitTransaction body (standalone) — fixture variant 0
    writer.writeVariant(0); // CommitTransaction
    using commitTxId = makeTransactionId(0x01);
    commitTxId.encode(writer);
    {
      using commitAttested = new Attested(makeEvent(), makeAttestationSetEmpty());
      writer.writeVec(
        [commitAttested],
        (w, e) => e.encode(w, (w2, ev) => ev.encode(w2)),
      );
    }

    // Get body (standalone) — fixture variant 1
    writer.writeVariant(1);
    using getCollection = makeCollectionId('users');
    getCollection.encode(writer);
    {
      using getId0 = makeEntityId(0x40);
      using getId1 = makeEntityId(0x50);
      writer.writeVec([getId0, getId1], (w, id) => id.encode(w));
    }

    // GetEvents body (standalone) — fixture variant 2
    writer.writeVariant(2);
    using getEventsCollection = makeCollectionId('users');
    getEventsCollection.encode(writer);
    {
      using getEventsId0 = makeEventId(0x60);
      writer.writeVec([getEventsId0], (w, id) => id.encode(w));
    }

    // Fetch body (standalone) — fixture variant 3
    writer.writeVariant(3);
    using fetchCollection = makeCollectionId('users');
    fetchCollection.encode(writer);
    encodeSelection(writer);
    {
      using fetchKnown = makeKnownEntity();
      writer.writeVec([fetchKnown], (w, ke) => ke.encode(w));
    }

    // SubscribeQuery body (standalone) — fixture variant 4
    writer.writeVariant(4);
    using subQueryId = makeQueryId(99);
    subQueryId.encode(writer);
    using subCollection = makeCollectionId('users');
    subCollection.encode(writer);
    encodeSelection(writer);
    writer.writeU32(1); // version
    writer.writeVec([] as KnownEntity[], (w, ke) => ke.encode(w));

    expectBytesEqual(writer.finish(), fixture, 'request.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// RESPONSE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════
// Fixture variant numbering (pre-EntitiesSubscribed):
//   CommitComplete=0, Fetch=1, Get=2, GetEvents=3, QuerySubscribed=4, Success=5, Error=6
// Current TS class numbering (post-EntitiesSubscribed):
//   CommitComplete=0, Fetch=1, Get=2, EntitiesSubscribed=3, GetEvents=4, QuerySubscribed=5, Success=6, Error=7
// The first NodeResponse has body=Success (fixture variant 5, TS variant 6),
// so we manually decode/encode the full struct.

describe('response.bin fixture', () => {
  test('decode: NodeResponse and all body variants', () => {
    const data = loadFixture('response.bin');
    const reader = new BincodeReader(data);

    // NodeResponse (Success) — manually decode due to variant mismatch
    using respRequestId = RequestId.decode(reader);
    { using expected = makeRequestId(0x01); expect(respRequestId.toUlidString()).toBe(expected.toUlidString()); }
    using respFrom = EntityId.decode(reader);
    { using expected = makeEntityId(0x10); expect(respFrom.bytes).toEqual(expected.bytes); }
    using respTo = EntityId.decode(reader);
    { using expected = makeEntityId(0x20); expect(respTo.bytes).toEqual(expected.bytes); }
    const respBodyVariant = reader.readVariant();
    expect(respBodyVariant).toBe(5); // Success in fixture

    // CommitComplete body (standalone) — fixture variant 0
    const commitVariant = reader.readVariant();
    expect(commitVariant).toBe(0);
    using commitId = TransactionId.decode(reader);
    { using expected = makeTransactionId(0x02); expect(commitId.toUlidString()).toBe(expected.toUlidString()); }

    // Fetch body (standalone) — fixture variant 1
    const fetchVariant = reader.readVariant();
    expect(fetchVariant).toBe(1);
    const fetchDeltas = reader.readVec(r => EntityDelta.decode(r));
    expect(fetchDeltas.length).toBe(1);
    { using expected = makeEntityId(0x30); expect(fetchDeltas[0].entityId.bytes).toEqual(expected.bytes); }
    expect(fetchDeltas[0].collection.asStr()).toBe('users');
    expect(fetchDeltas[0].content.type).toBe('StateSnapshot');
    for (const d of fetchDeltas) d.drop();

    // Get body (standalone) — fixture variant 2
    const getVariant = reader.readVariant();
    expect(getVariant).toBe(2);
    const getStates = reader.readVec(r => Attested.decode(r, r2 => EntityState.decode(r2)));
    expect(getStates.length).toBe(1);
    { using expected = makeEntityId(0x00); expect(getStates[0].payload.entityId.bytes).toEqual(expected.bytes); }
    expect(getStates[0].attestations.length).toBe(0);
    for (const s of getStates) s.drop();

    // GetEvents body (standalone) — fixture variant 3 (TS class: 4)
    const getEventsVariant = reader.readVariant();
    expect(getEventsVariant).toBe(3);
    const getEvents = reader.readVec(r => Attested.decode(r, r2 => Event.decode(r2)));
    expect(getEvents.length).toBe(1);
    expect(getEvents[0].payload.collection.asStr()).toBe('test_collection');
    expect(getEvents[0].attestations.length).toBe(0);
    for (const e of getEvents) e.drop();

    // QuerySubscribed body (standalone) — fixture variant 4 (TS class: 5)
    const qsVariant = reader.readVariant();
    expect(qsVariant).toBe(4);
    using qsQueryId = QueryId.decode(reader);
    { using expected = makeQueryId(42); expect(qsQueryId.toUlidString()).toBe(expected.toUlidString()); }
    const qsDeltas = reader.readVec(r => EntityDelta.decode(r));
    expect(qsDeltas.length).toBe(1);
    { using expected = makeEntityId(0x40); expect(qsDeltas[0].entityId.bytes).toEqual(expected.bytes); }
    expect(qsDeltas[0].collection.asStr()).toBe('posts');
    expect(qsDeltas[0].content.type).toBe('EventBridge');
    for (const d of qsDeltas) d.drop();

    // Success body (standalone) — fixture variant 5 (TS class: 6)
    const successVariant = reader.readVariant();
    expect(successVariant).toBe(5);

    // Error body (standalone) — fixture variant 6 (TS class: 7)
    const errorVariant = reader.readVariant();
    expect(errorVariant).toBe(6);
    const errorMsg = reader.readString();
    expect(errorMsg).toBe('something went wrong');

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('response.bin');
    const writer = new BincodeWriter();

    // NodeResponse (Success) — manually encode due to variant mismatch
    using respReqId = makeRequestId(0x01);
    respReqId.encode(writer);
    using respFrom = makeEntityId(0x10);
    respFrom.encode(writer);
    using respTo = makeEntityId(0x20);
    respTo.encode(writer);
    writer.writeVariant(5); // Success in fixture

    // CommitComplete body (standalone) — fixture variant 0
    writer.writeVariant(0);
    using commitTxId = makeTransactionId(0x02);
    commitTxId.encode(writer);

    // Fetch body (standalone) — fixture variant 1
    writer.writeVariant(1);
    {
      using fetchDelta = new EntityDelta(
        makeEntityId(0x30),
        makeCollectionId('users'),
        new DeltaContent('StateSnapshot', { state: makeStateFragment() }),
      );
      writer.writeVec(
        [fetchDelta],
        (w, d) => d.encode(w),
      );
    }

    // Get body (standalone) — fixture variant 2
    writer.writeVariant(2);
    {
      using getAttested = new Attested(makeEntityState(), makeAttestationSetEmpty());
      writer.writeVec(
        [getAttested],
        (w, s) => s.encode(w, (w2, es) => es.encode(w2)),
      );
    }

    // GetEvents body (standalone) — fixture variant 3
    writer.writeVariant(3);
    {
      using getEventsAttested = new Attested(makeEvent(), makeAttestationSetEmpty());
      writer.writeVec(
        [getEventsAttested],
        (w, e) => e.encode(w, (w2, ev) => ev.encode(w2)),
      );
    }

    // QuerySubscribed body (standalone) — fixture variant 4
    writer.writeVariant(4);
    using qsQueryId = makeQueryId(42);
    qsQueryId.encode(writer);
    {
      using qsDelta = new EntityDelta(
        makeEntityId(0x40),
        makeCollectionId('posts'),
        new DeltaContent('EventBridge', { events: [makeEventFragment()] }),
      );
      writer.writeVec(
        [qsDelta],
        (w, d) => d.encode(w),
      );
    }

    // Success body (standalone) — fixture variant 5
    writer.writeVariant(5);

    // Error body (standalone) — fixture variant 6
    writer.writeVariant(6);
    writer.writeString('something went wrong');

    expectBytesEqual(writer.finish(), fixture, 'response.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// CAUSAL FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('causal.bin fixture', () => {
  test('decode: all CausalRelation variants and CausalAssertionFragment', () => {
    const data = loadFixture('causal.bin');
    const reader = new BincodeReader(data);

    using equal = CausalRelation.decode(reader);
    expect(equal.type).toBe('Equal');

    using strictDescends = CausalRelation.decode(reader);
    expect(strictDescends.type).toBe('StrictDescends');

    using strictAscends = CausalRelation.decode(reader);
    expect(strictAscends.type).toBe('StrictAscends');

    using divergedSince = CausalRelation.decode(reader);
    expect(divergedSince.type).toBe('DivergedSince');
    if (divergedSince.is('DivergedSince')) {
      expect(divergedSince.value.meet.length).toBe(1);
      expect(divergedSince.value.subject.length).toBe(1);
      expect(divergedSince.value.other.length).toBe(1);
      { using expected = makeEventId(0xA0); expect(divergedSince.value.subject.asSlice()[0].bytes).toEqual(expected.bytes); }
      { using expected = makeEventId(0xB0); expect(divergedSince.value.other.asSlice()[0].bytes).toEqual(expected.bytes); }
    }

    using disjointSome = CausalRelation.decode(reader);
    expect(disjointSome.type).toBe('Disjoint');
    if (disjointSome.is('Disjoint')) {
      expect(disjointSome.value.gca).not.toBeNull();
      expect(disjointSome.value.gca!.length).toBe(1);
      { using expected = makeEventId(0xC0); expect(disjointSome.value.subjectRoot.bytes).toEqual(expected.bytes); }
      { using expected = makeEventId(0xD0); expect(disjointSome.value.otherRoot.bytes).toEqual(expected.bytes); }
    }

    using disjointNone = CausalRelation.decode(reader);
    expect(disjointNone.type).toBe('Disjoint');
    if (disjointNone.is('Disjoint')) {
      expect(disjointNone.value.gca).toBeNull();
      { using expected = makeEventId(0xE0); expect(disjointNone.value.subjectRoot.bytes).toEqual(expected.bytes); }
      { using expected = makeEventId(0xF0); expect(disjointNone.value.otherRoot.bytes).toEqual(expected.bytes); }
    }

    using budgetExceeded = CausalRelation.decode(reader);
    expect(budgetExceeded.type).toBe('BudgetExceeded');
    if (budgetExceeded.is('BudgetExceeded')) {
      { using expected = makeEventId(0x01); expect(budgetExceeded.value.subject.asSlice()[0].bytes).toEqual(expected.bytes); }
      { using expected = makeEventId(0x02); expect(budgetExceeded.value.other.asSlice()[0].bytes).toEqual(expected.bytes); }
    }

    using causalFragment = CausalAssertionFragment.decode(reader);
    expect(causalFragment.relation.type).toBe('StrictDescends');
    expect(causalFragment.attestations.length).toBe(2);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('causal.bin');
    const writer = new BincodeWriter();

    using crEqual = new CausalRelation('Equal', {});
    crEqual.encode(writer);
    using crStrictDescends = new CausalRelation('StrictDescends', {});
    crStrictDescends.encode(writer);
    using crStrictAscends = new CausalRelation('StrictAscends', {});
    crStrictAscends.encode(writer);
    using crDiverged = new CausalRelation('DivergedSince', {
      meet: makeClockSingle(),
      subject: Clock.new([makeEventId(0xA0)]),
      other: Clock.new([makeEventId(0xB0)]),
    });
    crDiverged.encode(writer);
    using crDisjointSome = new CausalRelation('Disjoint', {
      gca: makeClockSingle(),
      subjectRoot: makeEventId(0xC0),
      otherRoot: makeEventId(0xD0),
    });
    crDisjointSome.encode(writer);
    using crDisjointNone = new CausalRelation('Disjoint', {
      gca: null,
      subjectRoot: makeEventId(0xE0),
      otherRoot: makeEventId(0xF0),
    });
    crDisjointNone.encode(writer);
    using crBudgetExceeded = new CausalRelation('BudgetExceeded', {
      subject: Clock.new([makeEventId(0x01)]),
      other: Clock.new([makeEventId(0x02)]),
    });
    crBudgetExceeded.encode(writer);

    using causalFragment = new CausalAssertionFragment(
      new CausalRelation('StrictDescends', {}),
      makeAttestationSetTwo(),
    );
    causalFragment.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'causal.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// DELTA FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('delta.bin fixture', () => {
  test('decode: DeltaContent variants, EntityDelta variants, KnownEntity', () => {
    const data = loadFixture('delta.bin');
    const reader = new BincodeReader(data);

    // StateSnapshot
    using stateSnapshot = DeltaContent.decode(reader);
    expect(stateSnapshot.type).toBe('StateSnapshot');
    if (stateSnapshot.is('StateSnapshot')) {
      expect(stateSnapshot.value.state.attestations.length).toBe(2);
    }

    // EventBridge
    using eventBridge = DeltaContent.decode(reader);
    expect(eventBridge.type).toBe('EventBridge');
    if (eventBridge.is('EventBridge')) {
      expect(eventBridge.value.events.length).toBe(1);
    }

    // StateAndRelation
    using stateAndRelation = DeltaContent.decode(reader);
    expect(stateAndRelation.type).toBe('StateAndRelation');
    if (stateAndRelation.is('StateAndRelation')) {
      expect(stateAndRelation.value.relation.relation.type).toBe('Equal');
    }

    // EntityDelta (snapshot)
    using entityDeltaSnapshot = EntityDelta.decode(reader);
    { using expected = makeEntityId(0x10); expect(entityDeltaSnapshot.entityId.bytes).toEqual(expected.bytes); }
    expect(entityDeltaSnapshot.collection.asStr()).toBe('test_collection');
    expect(entityDeltaSnapshot.content.type).toBe('StateSnapshot');

    // EntityDelta (bridge)
    using entityDeltaBridge = EntityDelta.decode(reader);
    { using expected = makeEntityId(0x20); expect(entityDeltaBridge.entityId.bytes).toEqual(expected.bytes); }
    expect(entityDeltaBridge.content.type).toBe('EventBridge');

    // EntityDelta (state+relation)
    using entityDeltaStateRel = EntityDelta.decode(reader);
    { using expected = makeEntityId(0x30); expect(entityDeltaStateRel.entityId.bytes).toEqual(expected.bytes); }
    expect(entityDeltaStateRel.content.type).toBe('StateAndRelation');

    // KnownEntity
    using knownEntity = KnownEntity.decode(reader);
    { using expected = makeEntityId(0x20); expect(knownEntity.entityId.bytes).toEqual(expected.bytes); }
    expect(knownEntity.head.length).toBe(1);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('delta.bin');
    const writer = new BincodeWriter();

    using dcSnapshot = new DeltaContent('StateSnapshot', { state: makeStateFragment() });
    dcSnapshot.encode(writer);
    using dcBridge = new DeltaContent('EventBridge', { events: [makeEventFragment()] });
    dcBridge.encode(writer);
    using dcStateRel = new DeltaContent('StateAndRelation', {
      state: makeStateFragment(),
      relation: makeCausalAssertionFragment(),
    });
    dcStateRel.encode(writer);

    using edSnapshot = new EntityDelta(
      makeEntityId(0x10),
      makeCollectionId('test_collection'),
      new DeltaContent('StateSnapshot', { state: makeStateFragment() }),
    );
    edSnapshot.encode(writer);

    using edBridge = new EntityDelta(
      makeEntityId(0x20),
      makeCollectionId('test_collection'),
      new DeltaContent('EventBridge', { events: [makeEventFragment()] }),
    );
    edBridge.encode(writer);

    using edStateRel = new EntityDelta(
      makeEntityId(0x30),
      makeCollectionId('test_collection'),
      new DeltaContent('StateAndRelation', {
        state: makeStateFragment(),
        relation: makeCausalAssertionFragment(),
      }),
    );
    edStateRel.encode(writer);

    using knownEntity = makeKnownEntity();
    knownEntity.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'delta.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// UPDATE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('update.bin fixture', () => {
  test('decode: NodeUpdate, SubscriptionUpdateItem, UpdateContent, MembershipChange, NodeUpdateAck', () => {
    const data = loadFixture('update.bin');
    const reader = new BincodeReader(data);

    // NodeUpdate
    using nodeUpdate = NodeUpdate.decode(reader);
    { using expected = makeUpdateId(0x01); expect(nodeUpdate.id.toUlidString()).toBe(expected.toUlidString()); }
    { using expected = makeEntityId(0x10); expect(nodeUpdate.from.bytes).toEqual(expected.bytes); }
    { using expected = makeEntityId(0x20); expect(nodeUpdate.to.bytes).toEqual(expected.bytes); }
    expect(nodeUpdate.body.type).toBe('SubscriptionUpdate');
    if (nodeUpdate.body.is('SubscriptionUpdate')) {
      expect(nodeUpdate.body.value.items.length).toBe(1);
      const item = nodeUpdate.body.value.items[0];
      { using expected = makeEntityId(0x30); expect(item.entityId.bytes).toEqual(expected.bytes); }
      expect(item.collection.asStr()).toBe('users');
      expect(item.content.type).toBe('EventOnly');
      expect(item.predicateRelevance.length).toBe(1);
      expect(item.predicateRelevance[0][1].type).toBe('Initial');
    }

    // SubscriptionUpdateItem (standalone)
    using subItem = SubscriptionUpdateItem.decode(reader);
    { using expected = makeEntityId(0x40); expect(subItem.entityId.bytes).toEqual(expected.bytes); }
    expect(subItem.collection.asStr()).toBe('posts');
    expect(subItem.content.type).toBe('StateAndEvent');
    expect(subItem.predicateRelevance.length).toBe(2);
    expect(subItem.predicateRelevance[0][1].type).toBe('Add');
    expect(subItem.predicateRelevance[1][1].type).toBe('Remove');

    // EventOnly (standalone)
    using eventOnly = UpdateContent.decode(reader);
    expect(eventOnly.type).toBe('EventOnly');
    if (eventOnly.is('EventOnly')) {
      expect(eventOnly.value._0.length).toBe(1);
    }

    // StateAndEvent (standalone)
    using stateAndEvent = UpdateContent.decode(reader);
    expect(stateAndEvent.type).toBe('StateAndEvent');
    if (stateAndEvent.is('StateAndEvent')) {
      expect(stateAndEvent.value._1.length).toBe(1);
    }

    // MembershipChange variants
    using initial = MembershipChange.decode(reader);
    expect(initial.type).toBe('Initial');
    using add = MembershipChange.decode(reader);
    expect(add.type).toBe('Add');
    using remove = MembershipChange.decode(reader);
    expect(remove.type).toBe('Remove');

    // NodeUpdateAck
    using nodeUpdateAck = NodeUpdateAck.decode(reader);
    { using expected = makeUpdateId(0x02); expect(nodeUpdateAck.id.toUlidString()).toBe(expected.toUlidString()); }
    { using expected = makeEntityId(0x50); expect(nodeUpdateAck.from.bytes).toEqual(expected.bytes); }
    { using expected = makeEntityId(0x60); expect(nodeUpdateAck.to.bytes).toEqual(expected.bytes); }
    expect(nodeUpdateAck.body.type).toBe('Success');

    // NodeUpdateAckBody::Success (standalone)
    using ackSuccess = NodeUpdateAckBody.decode(reader);
    expect(ackSuccess.type).toBe('Success');

    // NodeUpdateAckBody::Error (standalone)
    using ackError = NodeUpdateAckBody.decode(reader);
    expect(ackError.type).toBe('Error');
    if (ackError.is('Error')) {
      expect(ackError.value._0).toBe('update failed');
    }

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('update.bin');
    const writer = new BincodeWriter();

    // NodeUpdate
    using nodeUpdate = new NodeUpdate(
      makeUpdateId(0x01),
      makeEntityId(0x10),
      makeEntityId(0x20),
      new NodeUpdateBody('SubscriptionUpdate', {
        items: [
          new SubscriptionUpdateItem(
            makeEntityId(0x30),
            makeCollectionId('users'),
            new UpdateContent('EventOnly', { _0: [makeEventFragment()] }),
            [[makeQueryId(1), new MembershipChange('Initial', {})]],
          ),
        ],
      }),
    );
    nodeUpdate.encode(writer);

    // SubscriptionUpdateItem (standalone)
    using subItem = new SubscriptionUpdateItem(
      makeEntityId(0x40),
      makeCollectionId('posts'),
      new UpdateContent('StateAndEvent', { _0: makeStateFragment(), _1: [makeEventFragment()] }),
      [
        [makeQueryId(2), new MembershipChange('Add', {})],
        [makeQueryId(3), new MembershipChange('Remove', {})],
      ],
    );
    subItem.encode(writer);

    // EventOnly (standalone)
    using eventOnly = new UpdateContent('EventOnly', { _0: [makeEventFragment()] });
    eventOnly.encode(writer);

    // StateAndEvent (standalone)
    using stateAndEvent = new UpdateContent('StateAndEvent', {
      _0: makeStateFragment(),
      _1: [makeEventFragment()],
    });
    stateAndEvent.encode(writer);

    // MembershipChange variants
    using mcInitial = new MembershipChange('Initial', {});
    mcInitial.encode(writer);
    using mcAdd = new MembershipChange('Add', {});
    mcAdd.encode(writer);
    using mcRemove = new MembershipChange('Remove', {});
    mcRemove.encode(writer);

    // NodeUpdateAck
    using nodeUpdateAck = new NodeUpdateAck(
      makeUpdateId(0x02),
      makeEntityId(0x50),
      makeEntityId(0x60),
      new NodeUpdateAckBody('Success', {}),
    );
    nodeUpdateAck.encode(writer);

    // NodeUpdateAckBody::Success (standalone)
    using ackSuccess = new NodeUpdateAckBody('Success', {});
    ackSuccess.encode(writer);

    // NodeUpdateAckBody::Error (standalone)
    using ackError = new NodeUpdateAckBody('Error', { _0: 'update failed' });
    ackError.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'update.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// MESSAGE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════
// NodeMessage::Response contains NodeResponse with NodeResponseBody.
// Fixture variant numbering for NodeResponseBody differs from current TS class,
// so we manually decode/encode NodeResponse bodies where needed.

describe('message.bin fixture', () => {
  test('decode: Presence message, PeerMessage, NodeMessage variants', () => {
    const data = loadFixture('message.bin');
    const reader = new BincodeReader(data);

    // Message::Presence
    using presenceMsg = Message.decode(reader);
    expect(presenceMsg.type).toBe('Presence');
    if (presenceMsg.is('Presence')) {
      { using expected = makeEntityId(0x01); expect(presenceMsg.value._0.nodeId.bytes).toEqual(expected.bytes); }
      expect(presenceMsg.value._0.durable).toBe(true);
      expect(presenceMsg.value._0.systemRoot).toBeNull();
    }

    // Message::PeerMessage(NodeMessage::Request) — Request body is Get (variant 1, same in both)
    using peerRequest = Message.decode(reader);
    expect(peerRequest.type).toBe('PeerMessage');
    if (peerRequest.is('PeerMessage')) {
      expect(peerRequest.value._0.type).toBe('Request');
      if (peerRequest.value._0.is('Request')) {
        expect(peerRequest.value._0.value.auth.length).toBe(1);
        expect(peerRequest.value._0.value.auth[0]._0).toEqual(new Uint8Array([0xAA, 0xBB]));
        expect(peerRequest.value._0.value.request.body.type).toBe('Get');
      }
    }

    // NodeMessage::Request (standalone) — body is Get (variant 1, same in both)
    using nodeMsgRequest = NodeMessage.decode(reader);
    expect(nodeMsgRequest.type).toBe('Request');
    if (nodeMsgRequest.is('Request')) {
      expect(nodeMsgRequest.value.auth.length).toBe(0);
        { using expected = makeRequestId(0x50); expect(nodeMsgRequest.value.request.id.toUlidString()).toBe(expected.toUlidString()); }
      if (nodeMsgRequest.value.request.body.is('Get')) {
        expect(nodeMsgRequest.value.request.body.value.collection.asStr()).toBe('items');
        expect(nodeMsgRequest.value.request.body.value.ids.length).toBe(0);
      }
    }

    // NodeMessage::Response (standalone) — body is Success (fixture variant 5, TS variant 6)
    // Manually decode due to variant mismatch
    const nmResponseVariant = reader.readVariant();
    expect(nmResponseVariant).toBe(1); // NodeMessage::Response
    using nmRespRequestId = RequestId.decode(reader);
    { using expected = makeRequestId(0x80); expect(nmRespRequestId.toUlidString()).toBe(expected.toUlidString()); }
    using nmRespFrom = EntityId.decode(reader);
    using nmRespTo = EntityId.decode(reader);
    const nmRespBodyVariant = reader.readVariant();
    expect(nmRespBodyVariant).toBe(5); // Success in fixture

    // NodeMessage::Update (standalone) — SubscriptionUpdate variant 0, same in both
    using nodeMsgUpdate = NodeMessage.decode(reader);
    expect(nodeMsgUpdate.type).toBe('Update');
    if (nodeMsgUpdate.is('Update')) {
      { using expected = makeUpdateId(0x01); expect(nodeMsgUpdate.value._0.id.toUlidString()).toBe(expected.toUlidString()); }
      expect(nodeMsgUpdate.value._0.body.type).toBe('SubscriptionUpdate');
      if (nodeMsgUpdate.value._0.body.is('SubscriptionUpdate')) {
        expect(nodeMsgUpdate.value._0.body.value.items.length).toBe(0);
      }
    }

    // NodeMessage::UpdateAck (standalone) — Success variant 0, same in both
    using nodeMsgUpdateAck = NodeMessage.decode(reader);
    expect(nodeMsgUpdateAck.type).toBe('UpdateAck');
    if (nodeMsgUpdateAck.is('UpdateAck')) {
      { using expected = makeUpdateId(0x02); expect(nodeMsgUpdateAck.value._0.id.toUlidString()).toBe(expected.toUlidString()); }
      expect(nodeMsgUpdateAck.value._0.body.type).toBe('Success');
    }

    // NodeMessage::UnsubscribeQuery (standalone)
    using nodeMsgUnsub = NodeMessage.decode(reader);
    expect(nodeMsgUnsub.type).toBe('UnsubscribeQuery');
    if (nodeMsgUnsub.is('UnsubscribeQuery')) {
      { using expected = makeEntityId(0xF0); expect(nodeMsgUnsub.value.from.bytes).toEqual(expected.bytes); }
      { using expected = makeQueryId(77); expect(nodeMsgUnsub.value.queryId.toUlidString()).toBe(expected.toUlidString()); }
    }

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('message.bin');
    const writer = new BincodeWriter();

    // Message::Presence
    using presenceMsg = new Message('Presence', {
      _0: new Presence(makeEntityId(0x01), true, null),
    });
    presenceMsg.encode(writer);

    // Message::PeerMessage(NodeMessage::Request with auth) — Get variant 1
    using peerRequestMsg = new Message('PeerMessage', {
      _0: new NodeMessage('Request', {
        auth: [new AuthData(new Uint8Array([0xAA, 0xBB]))],
        request: new NodeRequest(
          makeRequestId(0x10),
          makeEntityId(0x20),
          makeEntityId(0x30),
          new NodeRequestBody('Get', { collection: makeCollectionId('users'), ids: [makeEntityId(0x40)] }),
        ),
      }),
    });
    peerRequestMsg.encode(writer);

    // NodeMessage::Request (standalone, empty auth) — Get variant 1
    using nodeMsgRequest = new NodeMessage('Request', {
      auth: [],
      request: new NodeRequest(
        makeRequestId(0x50),
        makeEntityId(0x60),
        makeEntityId(0x70),
        new NodeRequestBody('Get', { collection: makeCollectionId('items'), ids: [] }),
      ),
    });
    nodeMsgRequest.encode(writer);

    // NodeMessage::Response (standalone) — manually encode due to variant mismatch
    writer.writeVariant(1); // NodeMessage::Response
    using nmRespReqId = makeRequestId(0x80);
    nmRespReqId.encode(writer);
    using nmRespFrom = makeEntityId(0x90);
    nmRespFrom.encode(writer);
    using nmRespTo = makeEntityId(0xA0);
    nmRespTo.encode(writer);
    writer.writeVariant(5); // Success in fixture

    // NodeMessage::Update (standalone)
    using nodeMsgUpdate = new NodeMessage('Update', {
      _0: new NodeUpdate(
        makeUpdateId(0x01),
        makeEntityId(0xB0),
        makeEntityId(0xC0),
        new NodeUpdateBody('SubscriptionUpdate', { items: [] }),
      ),
    });
    nodeMsgUpdate.encode(writer);

    // NodeMessage::UpdateAck (standalone)
    using nodeMsgUpdateAck = new NodeMessage('UpdateAck', {
      _0: new NodeUpdateAck(
        makeUpdateId(0x02),
        makeEntityId(0xD0),
        makeEntityId(0xE0),
        new NodeUpdateAckBody('Success', {}),
      ),
    });
    nodeMsgUpdateAck.encode(writer);

    // NodeMessage::UnsubscribeQuery (standalone)
    using nodeMsgUnsub = new NodeMessage('UnsubscribeQuery', {
      from: makeEntityId(0xF0),
      queryId: makeQueryId(77),
    });
    nodeMsgUnsub.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'message.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// PRESENCE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('presence.bin fixture', () => {
  test('decode: durable/no root, ephemeral/with root', () => {
    const data = loadFixture('presence.bin');
    const reader = new BincodeReader(data);

    // Presence: durable, no system_root
    using presenceDurable = Presence.decode(reader);
    { using expected = makeEntityId(0x01); expect(presenceDurable.nodeId.bytes).toEqual(expected.bytes); }
    expect(presenceDurable.durable).toBe(true);
    expect(presenceDurable.systemRoot).toBeNull();

    // Presence: ephemeral, with system_root
    using presenceEphemeral = Presence.decode(reader);
    { using expected = makeEntityId(0x02); expect(presenceEphemeral.nodeId.bytes).toEqual(expected.bytes); }
    expect(presenceEphemeral.durable).toBe(false);
    expect(presenceEphemeral.systemRoot).not.toBeNull();
    { using expected = makeEntityId(0x00); expect(presenceEphemeral.systemRoot!.payload.entityId.bytes).toEqual(expected.bytes); }
    expect(presenceEphemeral.systemRoot!.payload.collection.asStr()).toBe('test_collection');
    expect(presenceEphemeral.systemRoot!.attestations.length).toBe(2);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('presence.bin');
    const writer = new BincodeWriter();

    using presenceDurable = new Presence(makeEntityId(0x01), true, null);
    presenceDurable.encode(writer);

    using presenceEphemeral = new Presence(
      makeEntityId(0x02),
      false,
      new Attested(makeEntityState(), makeAttestationSetTwo()),
    );
    presenceEphemeral.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'presence.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// SYSTEM FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('system.bin fixture', () => {
  test('decode: SysRoot and Collection items', () => {
    const data = loadFixture('system.bin');
    const reader = new BincodeReader(data);

    using sysRoot = Item.decode(reader);
    expect(sysRoot.type).toBe('SysRoot');

    using collectionItem = Item.decode(reader);
    expect(collectionItem.type).toBe('Collection');
    if (collectionItem.is('Collection')) {
      expect(collectionItem.value.name).toBe('users');
    }

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('system.bin');
    const writer = new BincodeWriter();

    using sysRoot = new Item('SysRoot', {});
    sysRoot.encode(writer);
    using collectionItem = new Item('Collection', { name: 'users' });
    collectionItem.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'system.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// CAUSAL ASSERTION FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('causal_assertion.bin fixture', () => {
  test('decode: CausalAssertion values', () => {
    const data = loadFixture('causal_assertion.bin');
    const reader = new BincodeReader(data);

    using causalAssertion = CausalAssertion.decode(reader);
    { using expected = makeEntityId(0x10); expect(causalAssertion.entityId.bytes).toEqual(expected.bytes); }
    expect(causalAssertion.subject.length).toBe(1);
    expect(causalAssertion.other.length).toBe(3);
    expect(causalAssertion.relation.type).toBe('StrictDescends');

    using causalAssertionEqual = CausalAssertion.decode(reader);
    { using expected = makeEntityId(0x20); expect(causalAssertionEqual.entityId.bytes).toEqual(expected.bytes); }
    expect(causalAssertionEqual.subject.length).toBe(0);
    expect(causalAssertionEqual.other.length).toBe(0);
    expect(causalAssertionEqual.relation.type).toBe('Equal');

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('causal_assertion.bin');
    const writer = new BincodeWriter();

    using ca1 = new CausalAssertion(
      makeEntityId(0x10),
      makeClockSingle(),
      makeClockMulti(),
      new CausalRelation('StrictDescends', {}),
    );
    ca1.encode(writer);

    using ca2 = new CausalAssertion(
      makeEntityId(0x20),
      makeClockEmpty(),
      makeClockEmpty(),
      new CausalRelation('Equal', {}),
    );
    ca2.encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'causal_assertion.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// PRINCIPAL FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('principal.bin fixture', () => {
  test('decode and round-trip: empty struct', () => {
    const data = loadFixture('principal.bin');
    // Principal is a unit struct — bincode serializes as 0 bytes
    expect(data.length).toBe(0);

    // Round-trip: empty writer matches empty fixture
    const writer = new BincodeWriter();
    // No data to write for unit struct
    expectBytesEqual(writer.finish(), data, 'principal.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// ATTESTED EVENT FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('attested_event.bin fixture', () => {
  test('decode: Attested<Event> with and without attestations', () => {
    const data = loadFixture('attested_event.bin');
    const reader = new BincodeReader(data);

    // Attested<Event> with two attestations
    using attestedEvent = Attested.decode(reader, r => Event.decode(r));
    expect(attestedEvent.payload.collection.asStr()).toBe('test_collection');
    { using expected = makeEntityId(0x00); expect(attestedEvent.payload.entityId.bytes).toEqual(expected.bytes); }
    expect(attestedEvent.attestations.length).toBe(2);

    // Attested<Event> with empty attestations
    using attestedEventEmpty = Attested.decode(reader, r => Event.decode(r));
    expect(attestedEventEmpty.payload.collection.asStr()).toBe('test_collection');
    expect(attestedEventEmpty.attestations.length).toBe(0);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('attested_event.bin');
    const writer = new BincodeWriter();

    using attestedWithTwo = new Attested(makeEvent(), makeAttestationSetTwo());
    attestedWithTwo.encode(writer, (w, ev) => ev.encode(w));
    using attestedWithEmpty = new Attested(makeEvent(), makeAttestationSetEmpty());
    attestedWithEmpty.encode(writer, (w, ev) => ev.encode(w));

    expectBytesEqual(writer.finish(), fixture, 'attested_event.bin');
  });
});
