// TS-ONLY: cross-language bincode fixture validation
//
// These tests read binary fixture files generated by the Rust side
// (ankurah-ts-support/proto/tests/bincode_fixtures.rs) and validate
// that the TypeScript bincode codec produces identical results.
//
// For each fixture we do TWO checks:
//   1. Decode the .bin file and verify field values (Rust -> TS decode).
//   2. Construct matching TS values, encode them, and compare bytes (TS encode -> Rust).

import { describe, test, expect, beforeAll } from 'bun:test';
import { readFileSync, existsSync } from 'fs';
import path from 'path';

import {
  BincodeReader,
  BincodeWriter,
  EntityId,
  EventId,
  TransactionId,
  RequestId,
  QueryId,
  UpdateId,
  CollectionId,
  Clock,
  AuthData,
  Attestation,
  AttestationSet,
  Attested,
  Operation,
  OperationSet,
  StateBuffers,
  State,
  EntityState,
  Event,
  EventFragment,
  StateFragment,
  NodeRequest,
  NodeResponse,
  NodeUpdate,
  NodeUpdateAck,
  SubscriptionUpdateItem,
  Presence,
} from '../src/index';

import {
  encodeCausalRelation,
  decodeCausalRelation,
  CausalAssertionFragment,
  EntityDelta,
  encodeDeltaContent,
  decodeDeltaContent,
  KnownEntity,
} from '../src/request';

import type { CausalRelation, DeltaContent, NodeRequestBody, NodeResponseBody } from '../src/request';

import {
  encodeUpdateContent,
  decodeUpdateContent,
  encodeMembershipChange,
  decodeMembershipChange,
  encodeNodeUpdateBody,
  decodeNodeUpdateBody,
  encodeNodeUpdateAckBody,
  decodeNodeUpdateAckBody,
} from '../src/update';

import type { UpdateContent, MembershipChange, NodeUpdateBody, NodeUpdateAckBody } from '../src/update';

import {
  encodeMessage,
  decodeMessage,
  encodeNodeMessage,
  decodeNodeMessage,
} from '../src/message';

import type { Message, NodeMessage } from '../src/message';

import { encodeItem, decodeItem } from '../src/sys';
import type { Item } from '../src/sys';

import { ulidStringToBytes } from '../src/id';

// ── Fixture path resolution ─────────────────────────────────────────────────

const FIXTURE_DIR = path.resolve(__dirname, '../../../../ankurah-ts-support/proto/test_fixtures');

function loadFixture(name: string): Uint8Array {
  const filePath = path.join(FIXTURE_DIR, name);
  if (!existsSync(filePath)) {
    throw new Error(
      `Fixture file not found at ${filePath}. ` +
      `Ensure the ankurah-ts-support worktree exists at ../ankurah-ts-support ` +
      `with the ts-port-support branch checked out.`
    );
  }
  const buf = readFileSync(filePath);
  return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
}

// ── Deterministic value constructors (mirrors Rust helpers) ──────────────────

function makeEntityId(seed: number): EntityId {
  const bytes = new Uint8Array(16);
  for (let i = 0; i < 16; i++) {
    bytes[i] = (seed + i) & 0xff;
  }
  return EntityId.fromBytes(bytes);
}

function makeEventId(seed: number): EventId {
  const bytes = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    bytes[i] = (seed + i) & 0xff;
  }
  return EventId.fromBytes(bytes);
}

/**
 * Construct a ULID-based ID from a seed, matching the Rust pattern:
 *   format!("0000000000000000000000{:04}", seed)
 * which produces a 26-char Crockford Base32 string with the seed as decimal digits.
 * e.g. seed=0x10 (16) -> "00000000000000000000000016"
 *      seed=0x30 (48) -> "00000000000000000000000048"
 */
function makeUlidBytes(seed: number): Uint8Array {
  // Rust format!("{:04}", seed) uses decimal formatting
  const seedStr = seed.toString(10).padStart(4, '0');
  const ulidStr = '0000000000000000000000' + seedStr;
  return ulidStringToBytes(ulidStr);
}

function makeTransactionId(seed: number): TransactionId {
  return TransactionId.fromBytes(makeUlidBytes(seed));
}

function makeRequestId(seed: number): RequestId {
  return RequestId.fromBytes(makeUlidBytes(seed));
}

function makeUpdateId(seed: number): UpdateId {
  return UpdateId.fromBytes(makeUlidBytes(seed));
}

function makeQueryId(id: number): QueryId {
  return QueryId.test(BigInt(id));
}

function makeCollectionId(name: string): CollectionId {
  return CollectionId.from(name);
}

function makeClockEmpty(): Clock {
  return Clock.new([]);
}

function makeClockSingle(): Clock {
  return Clock.new([makeEventId(0x10)]);
}

function makeClockMulti(): Clock {
  return Clock.new([
    makeEventId(0x10),
    makeEventId(0x30),
    makeEventId(0x50),
  ]);
}

function makeOperation(diff: number[]): Operation {
  return new Operation(new Uint8Array(diff));
}

function makeOperationSet(): OperationSet {
  const map = new Map<string, Operation[]>();
  map.set('backend_a', [
    makeOperation([0xAA, 0xBB]),
    makeOperation([0xCC]),
  ]);
  map.set('backend_b', [
    makeOperation([0xDD, 0xEE, 0xFF]),
  ]);
  return new OperationSet(map);
}

function makeStateBuffers(): StateBuffers {
  const map = new Map<string, Uint8Array>();
  map.set('buf_alpha', new Uint8Array([0x01, 0x02, 0x03]));
  map.set('buf_beta', new Uint8Array([0x04, 0x05]));
  return new StateBuffers(map);
}

function makeState(): State {
  return new State(makeStateBuffers(), makeClockSingle());
}

function makeAttestation(bytes: number[]): Attestation {
  return new Attestation(new Uint8Array(bytes));
}

function makeAttestationSetEmpty(): AttestationSet {
  return new AttestationSet([]);
}

function makeAttestationSetTwo(): AttestationSet {
  return new AttestationSet([
    makeAttestation([0x42, 0x43]),
    makeAttestation([0x44, 0x45, 0x46]),
  ]);
}

function makeStateFragment(): StateFragment {
  return new StateFragment(makeState(), makeAttestationSetTwo());
}

function makeEventFragment(): EventFragment {
  return new EventFragment(
    makeOperationSet(),
    makeClockSingle(),
    makeAttestationSetEmpty(),
  );
}

function makeEntityState(): EntityState {
  return new EntityState(
    makeEntityId(0x00),
    makeCollectionId('test_collection'),
    makeState(),
  );
}

function makeEvent(): Event {
  return new Event(
    makeCollectionId('test_collection'),
    makeEntityId(0x00),
    makeOperationSet(),
    makeClockSingle(),
  );
}

function makeKnownEntity(): KnownEntity {
  return new KnownEntity(makeEntityId(0x20), makeClockSingle());
}

function makeCausalAssertionFragment(): CausalAssertionFragment {
  return new CausalAssertionFragment(
    { type: 'Equal' },
    makeAttestationSetTwo(),
  );
}

/**
 * Encode a Selection { predicate: name = 'test', order_by: None, limit: None }
 * in bincode format, matching the Rust make_selection() helper.
 *
 * Layout:
 *   Predicate::Comparison (variant 0)
 *     left: Expr::Path (variant 1)
 *       PathExpr { steps: ["name"] }
 *     operator: ComparisonOperator::Equal (variant 0)
 *     right: Expr::Literal (variant 0)
 *       Literal::String (variant 5) "test"
 *   order_by: None (0u8)
 *   limit: None (0u8)
 */
function encodeSelection(writer: BincodeWriter): void {
  // Predicate::Comparison = variant 0
  writer.writeVariant(0);
  // left: Expr::Path = variant 1
  writer.writeVariant(1);
  // PathExpr { steps: Vec<String> }
  writer.writeLength(1); // vec len = 1
  writer.writeString('name'); // steps[0]
  // operator: ComparisonOperator::Equal = variant 0
  writer.writeVariant(0);
  // right: Expr::Literal = variant 0
  writer.writeVariant(0);
  // Literal::String = variant 5
  writer.writeVariant(5);
  writer.writeString('test');
  // order_by: Option::None
  writer.writeU8(0);
  // limit: Option::None
  writer.writeU8(0);
}

/**
 * Read past a Selection in the reader (skip the known bytes).
 * Returns the raw bytes consumed for verification.
 */
function skipSelection(reader: BincodeReader): void {
  // Predicate variant
  const predVariant = reader.readVariant();
  expect(predVariant).toBe(0); // Comparison
  // left: Expr variant
  const leftVariant = reader.readVariant();
  expect(leftVariant).toBe(1); // Path
  // PathExpr steps
  const stepsLen = reader.readLength();
  expect(stepsLen).toBe(1);
  const step0 = reader.readString();
  expect(step0).toBe('name');
  // operator
  const opVariant = reader.readVariant();
  expect(opVariant).toBe(0); // Equal
  // right: Expr variant
  const rightVariant = reader.readVariant();
  expect(rightVariant).toBe(0); // Literal
  // Literal::String variant
  const litVariant = reader.readVariant();
  expect(litVariant).toBe(5); // String
  const litStr = reader.readString();
  expect(litStr).toBe('test');
  // order_by: None
  const orderBy = reader.readU8();
  expect(orderBy).toBe(0);
  // limit: None
  const limit = reader.readU8();
  expect(limit).toBe(0);
}

// ── Helper: compare encoded bytes to fixture ─────────────────────────────────

function expectBytesEqual(actual: Uint8Array, expected: Uint8Array, label: string): void {
  if (actual.length !== expected.length) {
    // Find first difference for debugging
    const minLen = Math.min(actual.length, expected.length);
    for (let i = 0; i < minLen; i++) {
      if (actual[i] !== expected[i]) {
        throw new Error(
          `${label}: length mismatch (actual ${actual.length} vs expected ${expected.length}), ` +
          `first difference at byte ${i}: actual 0x${actual[i].toString(16).padStart(2, '0')} ` +
          `vs expected 0x${expected[i].toString(16).padStart(2, '0')}`
        );
      }
    }
    throw new Error(`${label}: length mismatch (actual ${actual.length} vs expected ${expected.length})`);
  }
  for (let i = 0; i < actual.length; i++) {
    if (actual[i] !== expected[i]) {
      throw new Error(
        `${label}: mismatch at byte ${i}: actual 0x${actual[i].toString(16).padStart(2, '0')} ` +
        `vs expected 0x${expected[i].toString(16).padStart(2, '0')}`
      );
    }
  }
}

// ── Test: verify fixture directory exists ────────────────────────────────────

beforeAll(() => {
  if (!existsSync(FIXTURE_DIR)) {
    throw new Error(
      `Fixture directory not found at ${FIXTURE_DIR}. ` +
      `Ensure the ankurah-ts-support worktree exists at ../ankurah-ts-support ` +
      `with the ts-port-support branch checked out.`
    );
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// IDS FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('ids.bin fixture', () => {
  test('decode: EntityId, EventId, TransactionId, RequestId, QueryId, UpdateId, CollectionId', () => {
    const data = loadFixture('ids.bin');
    const reader = new BincodeReader(data);

    // EntityId: bytes [0,1,2,...,15]
    const entityId = EntityId.decode(reader);
    expect(entityId.bytes).toEqual(new Uint8Array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]));

    // EventId: bytes [0,1,2,...,31]
    const eventId = EventId.decode(reader);
    expect(eventId.bytes).toEqual(new Uint8Array([
      0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
      16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
    ]));

    // TransactionId: ULID string "00000000000000000000000016" (seed=0x10=16)
    const transactionId = TransactionId.decode(reader);
    expect(transactionId.toUlidString()).toBe('00000000000000000000000016');

    // RequestId: ULID string "00000000000000000000000032" (seed=0x20=32)
    const requestId = RequestId.decode(reader);
    expect(requestId.toUlidString()).toBe('00000000000000000000000032');

    // QueryId: test(42) = Ulid::from_parts(42, 0)
    const queryId = QueryId.decode(reader);
    expect(queryId.toUlidString()).toBe(QueryId.test(42n).toUlidString());

    // UpdateId: ULID string "00000000000000000000000048" (seed=0x30=48)
    const updateId = UpdateId.decode(reader);
    expect(updateId.toUlidString()).toBe('00000000000000000000000048');

    // CollectionId: "test_collection"
    const collectionId = CollectionId.decode(reader);
    expect(collectionId.value).toBe('test_collection');

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('ids.bin');
    const writer = new BincodeWriter();

    // EntityId: bytes [0..15]
    EntityId.fromBytes(new Uint8Array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])).encode(writer);

    // EventId: bytes [0..31]
    EventId.fromBytes(new Uint8Array([
      0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
      16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
    ])).encode(writer);

    makeTransactionId(0x10).encode(writer);
    makeRequestId(0x20).encode(writer);
    makeQueryId(42).encode(writer);
    makeUpdateId(0x30).encode(writer);
    makeCollectionId('test_collection').encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'ids.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// CLOCK FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('clock.bin fixture', () => {
  test('decode: empty, single, multi clocks', () => {
    const data = loadFixture('clock.bin');
    const reader = new BincodeReader(data);

    const empty = Clock.decode(reader);
    expect(empty.length).toBe(0);

    const single = Clock.decode(reader);
    expect(single.length).toBe(1);
    expect(single.asSlice()[0].bytes).toEqual(makeEventId(0x10).bytes);

    const multi = Clock.decode(reader);
    expect(multi.length).toBe(3);
    expect(multi.asSlice()[0].bytes).toEqual(makeEventId(0x10).bytes);
    expect(multi.asSlice()[1].bytes).toEqual(makeEventId(0x30).bytes);
    expect(multi.asSlice()[2].bytes).toEqual(makeEventId(0x50).bytes);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('clock.bin');
    const writer = new BincodeWriter();

    makeClockEmpty().encode(writer);
    makeClockSingle().encode(writer);
    makeClockMulti().encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'clock.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// AUTH FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('auth.bin fixture', () => {
  test('decode: AuthData, Attestation, AttestationSet, Attested<EntityState>', () => {
    const data = loadFixture('auth.bin');
    const reader = new BincodeReader(data);

    // AuthData with bytes
    const authDataBytes = AuthData.decode(reader);
    expect(authDataBytes.data).toEqual(new Uint8Array([0x01, 0x02, 0x03]));

    // AuthData empty
    const authDataEmpty = AuthData.decode(reader);
    expect(authDataEmpty.data).toEqual(new Uint8Array([]));

    // Attestation
    const attestation = Attestation.decode(reader);
    expect(attestation.data).toEqual(new Uint8Array([0x42, 0x43]));

    // AttestationSet empty
    const attestationSetEmpty = AttestationSet.decode(reader);
    expect(attestationSetEmpty.length).toBe(0);

    // AttestationSet with two
    const attestationSetTwo = AttestationSet.decode(reader);
    expect(attestationSetTwo.length).toBe(2);
    expect(attestationSetTwo.attestations[0].data).toEqual(new Uint8Array([0x42, 0x43]));
    expect(attestationSetTwo.attestations[1].data).toEqual(new Uint8Array([0x44, 0x45, 0x46]));

    // Attested<EntityState>
    const attested = Attested.decode(reader, r => EntityState.decode(r));
    expect(attested.payload.entityId.bytes).toEqual(makeEntityId(0x00).bytes);
    expect(attested.payload.collection.value).toBe('test_collection');
    expect(attested.attestations.length).toBe(2);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('auth.bin');
    const writer = new BincodeWriter();

    new AuthData(new Uint8Array([0x01, 0x02, 0x03])).encode(writer);
    new AuthData(new Uint8Array([])).encode(writer);
    makeAttestation([0x42, 0x43]).encode(writer);
    makeAttestationSetEmpty().encode(writer);
    makeAttestationSetTwo().encode(writer);

    const attested = new Attested(makeEntityState(), makeAttestationSetTwo());
    attested.encode(writer, (w, es) => es.encode(w));

    expectBytesEqual(writer.finish(), fixture, 'auth.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// DATA FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('data.bin fixture', () => {
  test('decode: Operation, OperationSet, StateBuffers, State, StateFragment, Event, EventFragment, EntityState', () => {
    const data = loadFixture('data.bin');
    const reader = new BincodeReader(data);

    // Operation
    const operation = Operation.decode(reader);
    expect(operation.diff).toEqual(new Uint8Array([0xAA, 0xBB, 0xCC]));

    // OperationSet
    const operationSet = OperationSet.decode(reader);
    expect(operationSet.map.size).toBe(2);
    const backendA = operationSet.get('backend_a')!;
    expect(backendA.length).toBe(2);
    expect(backendA[0].diff).toEqual(new Uint8Array([0xAA, 0xBB]));
    expect(backendA[1].diff).toEqual(new Uint8Array([0xCC]));
    const backendB = operationSet.get('backend_b')!;
    expect(backendB.length).toBe(1);
    expect(backendB[0].diff).toEqual(new Uint8Array([0xDD, 0xEE, 0xFF]));

    // StateBuffers
    const stateBuffers = StateBuffers.decode(reader);
    expect(stateBuffers.map.size).toBe(2);
    expect(stateBuffers.get('buf_alpha')).toEqual(new Uint8Array([0x01, 0x02, 0x03]));
    expect(stateBuffers.get('buf_beta')).toEqual(new Uint8Array([0x04, 0x05]));

    // State
    const state = State.decode(reader);
    expect(state.stateBuffers.map.size).toBe(2);
    expect(state.head.length).toBe(1);

    // StateFragment
    const stateFragment = StateFragment.decode(reader);
    expect(stateFragment.state.stateBuffers.map.size).toBe(2);
    expect(stateFragment.attestations.length).toBe(2);

    // Event
    const event = Event.decode(reader);
    expect(event.collection.value).toBe('test_collection');
    expect(event.entityId.bytes).toEqual(makeEntityId(0x00).bytes);
    expect(event.operations.map.size).toBe(2);
    expect(event.parent.length).toBe(1);

    // EventFragment
    const eventFragment = EventFragment.decode(reader);
    expect(eventFragment.operations.map.size).toBe(2);
    expect(eventFragment.parent.length).toBe(1);
    expect(eventFragment.attestations.length).toBe(0);

    // EntityState
    const entityState = EntityState.decode(reader);
    expect(entityState.entityId.bytes).toEqual(makeEntityId(0x00).bytes);
    expect(entityState.collection.value).toBe('test_collection');
    expect(entityState.state.head.length).toBe(1);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('data.bin');
    const writer = new BincodeWriter();

    makeOperation([0xAA, 0xBB, 0xCC]).encode(writer);
    makeOperationSet().encode(writer);
    makeStateBuffers().encode(writer);
    makeState().encode(writer);
    makeStateFragment().encode(writer);
    makeEvent().encode(writer);
    makeEventFragment().encode(writer);
    makeEntityState().encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'data.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// REQUEST FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('request.bin fixture', () => {
  test('decode: NodeRequest, CommitTransaction, Get, GetEvents, Fetch, SubscribeQuery', () => {
    const data = loadFixture('request.bin');
    const reader = new BincodeReader(data);

    // NodeRequest (Get variant)
    const nodeRequest = NodeRequest.decode(reader);
    expect(nodeRequest.id.toUlidString()).toBe(makeRequestId(0x01).toUlidString());
    expect(nodeRequest.to.bytes).toEqual(makeEntityId(0x10).bytes);
    expect(nodeRequest.from.bytes).toEqual(makeEntityId(0x20).bytes);
    expect(nodeRequest.body.type).toBe('Get');
    if (nodeRequest.body.type === 'Get') {
      expect(nodeRequest.body.collection.value).toBe('users');
      expect(nodeRequest.body.ids.length).toBe(1);
      expect(nodeRequest.body.ids[0].bytes).toEqual(makeEntityId(0x30).bytes);
    }

    // CommitTransaction body (standalone)
    const commitVariant = reader.readVariant();
    expect(commitVariant).toBe(0); // CommitTransaction
    const commitTxId = TransactionId.decode(reader);
    expect(commitTxId.toUlidString()).toBe(makeTransactionId(0x01).toUlidString());
    const commitEvents = reader.readVec(r => Attested.decode(r, r2 => Event.decode(r2)));
    expect(commitEvents.length).toBe(1);
    expect(commitEvents[0].attestations.length).toBe(0);

    // Get body (standalone)
    const getVariant = reader.readVariant();
    expect(getVariant).toBe(1); // Get
    const getCollection = CollectionId.decode(reader);
    expect(getCollection.value).toBe('users');
    const getIds = reader.readVec(r => EntityId.decode(r));
    expect(getIds.length).toBe(2);
    expect(getIds[0].bytes).toEqual(makeEntityId(0x40).bytes);
    expect(getIds[1].bytes).toEqual(makeEntityId(0x50).bytes);

    // GetEvents body (standalone)
    const getEventsVariant = reader.readVariant();
    expect(getEventsVariant).toBe(2); // GetEvents
    const getEventsCollection = CollectionId.decode(reader);
    expect(getEventsCollection.value).toBe('users');
    const getEventsIds = reader.readVec(r => EventId.decode(r));
    expect(getEventsIds.length).toBe(1);
    expect(getEventsIds[0].bytes).toEqual(makeEventId(0x60).bytes);

    // Fetch body (standalone) - contains Selection
    const fetchVariant = reader.readVariant();
    expect(fetchVariant).toBe(3); // Fetch
    const fetchCollection = CollectionId.decode(reader);
    expect(fetchCollection.value).toBe('users');
    // Skip selection (verified inline)
    skipSelection(reader);
    const fetchKnown = reader.readVec(r => KnownEntity.decode(r));
    expect(fetchKnown.length).toBe(1);
    expect(fetchKnown[0].entityId.bytes).toEqual(makeEntityId(0x20).bytes);

    // SubscribeQuery body (standalone) - contains Selection
    const subVariant = reader.readVariant();
    expect(subVariant).toBe(4); // SubscribeQuery
    const subQueryId = QueryId.decode(reader);
    expect(subQueryId.toUlidString()).toBe(makeQueryId(99).toUlidString());
    const subCollection = CollectionId.decode(reader);
    expect(subCollection.value).toBe('users');
    skipSelection(reader);
    const subVersion = reader.readU32();
    expect(subVersion).toBe(1);
    const subKnown = reader.readVec(r => KnownEntity.decode(r));
    expect(subKnown.length).toBe(0);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('request.bin');
    const writer = new BincodeWriter();

    // NodeRequest (full struct with Get body)
    const nodeRequest = new NodeRequest(
      makeRequestId(0x01),
      makeEntityId(0x10),
      makeEntityId(0x20),
      { type: 'Get', collection: makeCollectionId('users'), ids: [makeEntityId(0x30)] },
    );
    nodeRequest.encode(writer);

    // CommitTransaction body (standalone)
    writer.writeVariant(0); // CommitTransaction
    makeTransactionId(0x01).encode(writer);
    writer.writeVec(
      [new Attested(makeEvent(), makeAttestationSetEmpty())],
      (w, e) => e.encode(w, (w2, ev) => ev.encode(w2)),
    );

    // Get body (standalone)
    writer.writeVariant(1);
    makeCollectionId('users').encode(writer);
    writer.writeVec([makeEntityId(0x40), makeEntityId(0x50)], (w, id) => id.encode(w));

    // GetEvents body (standalone)
    writer.writeVariant(2);
    makeCollectionId('users').encode(writer);
    writer.writeVec([makeEventId(0x60)], (w, id) => id.encode(w));

    // Fetch body (standalone)
    writer.writeVariant(3);
    makeCollectionId('users').encode(writer);
    encodeSelection(writer);
    writer.writeVec([makeKnownEntity()], (w, ke) => ke.encode(w));

    // SubscribeQuery body (standalone)
    writer.writeVariant(4);
    makeQueryId(99).encode(writer);
    makeCollectionId('users').encode(writer);
    encodeSelection(writer);
    writer.writeU32(1); // version
    writer.writeVec([] as KnownEntity[], (w, ke) => ke.encode(w));

    expectBytesEqual(writer.finish(), fixture, 'request.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// RESPONSE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('response.bin fixture', () => {
  test('decode: NodeResponse and all body variants', () => {
    const data = loadFixture('response.bin');
    const reader = new BincodeReader(data);

    // NodeResponse (Success)
    const nodeResponse = NodeResponse.decode(reader);
    expect(nodeResponse.requestId.toUlidString()).toBe(makeRequestId(0x01).toUlidString());
    expect(nodeResponse.from.bytes).toEqual(makeEntityId(0x10).bytes);
    expect(nodeResponse.to.bytes).toEqual(makeEntityId(0x20).bytes);
    expect(nodeResponse.body.type).toBe('Success');

    // CommitComplete body (standalone)
    const commitVariant = reader.readVariant();
    expect(commitVariant).toBe(0);
    const commitId = TransactionId.decode(reader);
    expect(commitId.toUlidString()).toBe(makeTransactionId(0x02).toUlidString());

    // Fetch body (standalone)
    const fetchVariant = reader.readVariant();
    expect(fetchVariant).toBe(1);
    const fetchDeltas = reader.readVec(r => EntityDelta.decode(r));
    expect(fetchDeltas.length).toBe(1);
    expect(fetchDeltas[0].entityId.bytes).toEqual(makeEntityId(0x30).bytes);
    expect(fetchDeltas[0].collection.value).toBe('users');
    expect(fetchDeltas[0].content.type).toBe('StateSnapshot');

    // Get body (standalone)
    const getVariant = reader.readVariant();
    expect(getVariant).toBe(2);
    const getStates = reader.readVec(r => Attested.decode(r, r2 => EntityState.decode(r2)));
    expect(getStates.length).toBe(1);
    expect(getStates[0].payload.entityId.bytes).toEqual(makeEntityId(0x00).bytes);
    expect(getStates[0].attestations.length).toBe(0);

    // GetEvents body (standalone)
    const getEventsVariant = reader.readVariant();
    expect(getEventsVariant).toBe(3);
    const getEvents = reader.readVec(r => Attested.decode(r, r2 => Event.decode(r2)));
    expect(getEvents.length).toBe(1);
    expect(getEvents[0].payload.collection.value).toBe('test_collection');
    expect(getEvents[0].attestations.length).toBe(0);

    // QuerySubscribed body (standalone)
    const qsVariant = reader.readVariant();
    expect(qsVariant).toBe(4);
    const qsQueryId = QueryId.decode(reader);
    expect(qsQueryId.toUlidString()).toBe(makeQueryId(42).toUlidString());
    const qsDeltas = reader.readVec(r => EntityDelta.decode(r));
    expect(qsDeltas.length).toBe(1);
    expect(qsDeltas[0].entityId.bytes).toEqual(makeEntityId(0x40).bytes);
    expect(qsDeltas[0].collection.value).toBe('posts');
    expect(qsDeltas[0].content.type).toBe('EventBridge');

    // Success body (standalone)
    const successVariant = reader.readVariant();
    expect(successVariant).toBe(5);

    // Error body (standalone)
    const errorVariant = reader.readVariant();
    expect(errorVariant).toBe(6);
    const errorMsg = reader.readString();
    expect(errorMsg).toBe('something went wrong');

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('response.bin');
    const writer = new BincodeWriter();

    // NodeResponse (Success)
    new NodeResponse(
      makeRequestId(0x01),
      makeEntityId(0x10),
      makeEntityId(0x20),
      { type: 'Success' },
    ).encode(writer);

    // CommitComplete body (standalone)
    writer.writeVariant(0);
    makeTransactionId(0x02).encode(writer);

    // Fetch body (standalone)
    writer.writeVariant(1);
    writer.writeVec(
      [new EntityDelta(
        makeEntityId(0x30),
        makeCollectionId('users'),
        { type: 'StateSnapshot', state: makeStateFragment() },
      )],
      (w, d) => d.encode(w),
    );

    // Get body (standalone)
    writer.writeVariant(2);
    writer.writeVec(
      [new Attested(makeEntityState(), makeAttestationSetEmpty())],
      (w, s) => s.encode(w, (w2, es) => es.encode(w2)),
    );

    // GetEvents body (standalone)
    writer.writeVariant(3);
    writer.writeVec(
      [new Attested(makeEvent(), makeAttestationSetEmpty())],
      (w, e) => e.encode(w, (w2, ev) => ev.encode(w2)),
    );

    // QuerySubscribed body (standalone)
    writer.writeVariant(4);
    makeQueryId(42).encode(writer);
    writer.writeVec(
      [new EntityDelta(
        makeEntityId(0x40),
        makeCollectionId('posts'),
        { type: 'EventBridge', events: [makeEventFragment()] },
      )],
      (w, d) => d.encode(w),
    );

    // Success body (standalone)
    writer.writeVariant(5);

    // Error body (standalone)
    writer.writeVariant(6);
    writer.writeString('something went wrong');

    expectBytesEqual(writer.finish(), fixture, 'response.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// CAUSAL FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('causal.bin fixture', () => {
  test('decode: all CausalRelation variants and CausalAssertionFragment', () => {
    const data = loadFixture('causal.bin');
    const reader = new BincodeReader(data);

    const equal = decodeCausalRelation(reader);
    expect(equal.type).toBe('Equal');

    const strictDescends = decodeCausalRelation(reader);
    expect(strictDescends.type).toBe('StrictDescends');

    const strictAscends = decodeCausalRelation(reader);
    expect(strictAscends.type).toBe('StrictAscends');

    const divergedSince = decodeCausalRelation(reader);
    expect(divergedSince.type).toBe('DivergedSince');
    if (divergedSince.type === 'DivergedSince') {
      expect(divergedSince.meet.length).toBe(1);
      expect(divergedSince.subject.length).toBe(1);
      expect(divergedSince.other.length).toBe(1);
      expect(divergedSince.subject.asSlice()[0].bytes).toEqual(makeEventId(0xA0).bytes);
      expect(divergedSince.other.asSlice()[0].bytes).toEqual(makeEventId(0xB0).bytes);
    }

    const disjointSome = decodeCausalRelation(reader);
    expect(disjointSome.type).toBe('Disjoint');
    if (disjointSome.type === 'Disjoint') {
      expect(disjointSome.gca).not.toBeNull();
      expect(disjointSome.gca!.length).toBe(1);
      expect(disjointSome.subjectRoot.bytes).toEqual(makeEventId(0xC0).bytes);
      expect(disjointSome.otherRoot.bytes).toEqual(makeEventId(0xD0).bytes);
    }

    const disjointNone = decodeCausalRelation(reader);
    expect(disjointNone.type).toBe('Disjoint');
    if (disjointNone.type === 'Disjoint') {
      expect(disjointNone.gca).toBeNull();
      expect(disjointNone.subjectRoot.bytes).toEqual(makeEventId(0xE0).bytes);
      expect(disjointNone.otherRoot.bytes).toEqual(makeEventId(0xF0).bytes);
    }

    const budgetExceeded = decodeCausalRelation(reader);
    expect(budgetExceeded.type).toBe('BudgetExceeded');
    if (budgetExceeded.type === 'BudgetExceeded') {
      expect(budgetExceeded.subject.asSlice()[0].bytes).toEqual(makeEventId(0x01).bytes);
      expect(budgetExceeded.other.asSlice()[0].bytes).toEqual(makeEventId(0x02).bytes);
    }

    const causalFragment = CausalAssertionFragment.decode(reader);
    expect(causalFragment.relation.type).toBe('StrictDescends');
    expect(causalFragment.attestations.length).toBe(2);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('causal.bin');
    const writer = new BincodeWriter();

    encodeCausalRelation(writer, { type: 'Equal' });
    encodeCausalRelation(writer, { type: 'StrictDescends' });
    encodeCausalRelation(writer, { type: 'StrictAscends' });
    encodeCausalRelation(writer, {
      type: 'DivergedSince',
      meet: makeClockSingle(),
      subject: Clock.new([makeEventId(0xA0)]),
      other: Clock.new([makeEventId(0xB0)]),
    });
    encodeCausalRelation(writer, {
      type: 'Disjoint',
      gca: makeClockSingle(),
      subjectRoot: makeEventId(0xC0),
      otherRoot: makeEventId(0xD0),
    });
    encodeCausalRelation(writer, {
      type: 'Disjoint',
      gca: null,
      subjectRoot: makeEventId(0xE0),
      otherRoot: makeEventId(0xF0),
    });
    encodeCausalRelation(writer, {
      type: 'BudgetExceeded',
      subject: Clock.new([makeEventId(0x01)]),
      other: Clock.new([makeEventId(0x02)]),
    });

    new CausalAssertionFragment(
      { type: 'StrictDescends' },
      makeAttestationSetTwo(),
    ).encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'causal.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// DELTA FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('delta.bin fixture', () => {
  test('decode: DeltaContent variants, EntityDelta variants, KnownEntity', () => {
    const data = loadFixture('delta.bin');
    const reader = new BincodeReader(data);

    // StateSnapshot
    const stateSnapshot = decodeDeltaContent(reader);
    expect(stateSnapshot.type).toBe('StateSnapshot');
    if (stateSnapshot.type === 'StateSnapshot') {
      expect(stateSnapshot.state.attestations.length).toBe(2);
    }

    // EventBridge
    const eventBridge = decodeDeltaContent(reader);
    expect(eventBridge.type).toBe('EventBridge');
    if (eventBridge.type === 'EventBridge') {
      expect(eventBridge.events.length).toBe(1);
    }

    // StateAndRelation
    const stateAndRelation = decodeDeltaContent(reader);
    expect(stateAndRelation.type).toBe('StateAndRelation');
    if (stateAndRelation.type === 'StateAndRelation') {
      expect(stateAndRelation.relation.relation.type).toBe('Equal');
    }

    // EntityDelta (snapshot)
    const entityDeltaSnapshot = EntityDelta.decode(reader);
    expect(entityDeltaSnapshot.entityId.bytes).toEqual(makeEntityId(0x10).bytes);
    expect(entityDeltaSnapshot.collection.value).toBe('test_collection');
    expect(entityDeltaSnapshot.content.type).toBe('StateSnapshot');

    // EntityDelta (bridge)
    const entityDeltaBridge = EntityDelta.decode(reader);
    expect(entityDeltaBridge.entityId.bytes).toEqual(makeEntityId(0x20).bytes);
    expect(entityDeltaBridge.content.type).toBe('EventBridge');

    // EntityDelta (state+relation)
    const entityDeltaStateRel = EntityDelta.decode(reader);
    expect(entityDeltaStateRel.entityId.bytes).toEqual(makeEntityId(0x30).bytes);
    expect(entityDeltaStateRel.content.type).toBe('StateAndRelation');

    // KnownEntity
    const knownEntity = KnownEntity.decode(reader);
    expect(knownEntity.entityId.bytes).toEqual(makeEntityId(0x20).bytes);
    expect(knownEntity.head.length).toBe(1);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('delta.bin');
    const writer = new BincodeWriter();

    encodeDeltaContent(writer, { type: 'StateSnapshot', state: makeStateFragment() });
    encodeDeltaContent(writer, { type: 'EventBridge', events: [makeEventFragment()] });
    encodeDeltaContent(writer, {
      type: 'StateAndRelation',
      state: makeStateFragment(),
      relation: makeCausalAssertionFragment(),
    });

    new EntityDelta(
      makeEntityId(0x10),
      makeCollectionId('test_collection'),
      { type: 'StateSnapshot', state: makeStateFragment() },
    ).encode(writer);

    new EntityDelta(
      makeEntityId(0x20),
      makeCollectionId('test_collection'),
      { type: 'EventBridge', events: [makeEventFragment()] },
    ).encode(writer);

    new EntityDelta(
      makeEntityId(0x30),
      makeCollectionId('test_collection'),
      {
        type: 'StateAndRelation',
        state: makeStateFragment(),
        relation: makeCausalAssertionFragment(),
      },
    ).encode(writer);

    makeKnownEntity().encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'delta.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// UPDATE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('update.bin fixture', () => {
  test('decode: NodeUpdate, SubscriptionUpdateItem, UpdateContent, MembershipChange, NodeUpdateAck', () => {
    const data = loadFixture('update.bin');
    const reader = new BincodeReader(data);

    // NodeUpdate
    const nodeUpdate = NodeUpdate.decode(reader);
    expect(nodeUpdate.id.toUlidString()).toBe(makeUpdateId(0x01).toUlidString());
    expect(nodeUpdate.from.bytes).toEqual(makeEntityId(0x10).bytes);
    expect(nodeUpdate.to.bytes).toEqual(makeEntityId(0x20).bytes);
    expect(nodeUpdate.body.type).toBe('SubscriptionUpdate');
    if (nodeUpdate.body.type === 'SubscriptionUpdate') {
      expect(nodeUpdate.body.items.length).toBe(1);
      const item = nodeUpdate.body.items[0];
      expect(item.entityId.bytes).toEqual(makeEntityId(0x30).bytes);
      expect(item.collection.value).toBe('users');
      expect(item.content.type).toBe('EventOnly');
      expect(item.predicateRelevance.length).toBe(1);
      expect(item.predicateRelevance[0][1].type).toBe('Initial');
    }

    // SubscriptionUpdateItem (standalone)
    const subItem = SubscriptionUpdateItem.decode(reader);
    expect(subItem.entityId.bytes).toEqual(makeEntityId(0x40).bytes);
    expect(subItem.collection.value).toBe('posts');
    expect(subItem.content.type).toBe('StateAndEvent');
    expect(subItem.predicateRelevance.length).toBe(2);
    expect(subItem.predicateRelevance[0][1].type).toBe('Add');
    expect(subItem.predicateRelevance[1][1].type).toBe('Remove');

    // EventOnly (standalone)
    const eventOnly = decodeUpdateContent(reader);
    expect(eventOnly.type).toBe('EventOnly');
    if (eventOnly.type === 'EventOnly') {
      expect(eventOnly.events.length).toBe(1);
    }

    // StateAndEvent (standalone)
    const stateAndEvent = decodeUpdateContent(reader);
    expect(stateAndEvent.type).toBe('StateAndEvent');
    if (stateAndEvent.type === 'StateAndEvent') {
      expect(stateAndEvent.events.length).toBe(1);
    }

    // MembershipChange variants
    const initial = decodeMembershipChange(reader);
    expect(initial.type).toBe('Initial');
    const add = decodeMembershipChange(reader);
    expect(add.type).toBe('Add');
    const remove = decodeMembershipChange(reader);
    expect(remove.type).toBe('Remove');

    // NodeUpdateAck
    const nodeUpdateAck = NodeUpdateAck.decode(reader);
    expect(nodeUpdateAck.id.toUlidString()).toBe(makeUpdateId(0x02).toUlidString());
    expect(nodeUpdateAck.from.bytes).toEqual(makeEntityId(0x50).bytes);
    expect(nodeUpdateAck.to.bytes).toEqual(makeEntityId(0x60).bytes);
    expect(nodeUpdateAck.body.type).toBe('Success');

    // NodeUpdateAckBody::Success (standalone)
    const ackSuccess = decodeNodeUpdateAckBody(reader);
    expect(ackSuccess.type).toBe('Success');

    // NodeUpdateAckBody::Error (standalone)
    const ackError = decodeNodeUpdateAckBody(reader);
    expect(ackError.type).toBe('Error');
    if (ackError.type === 'Error') {
      expect(ackError.message).toBe('update failed');
    }

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('update.bin');
    const writer = new BincodeWriter();

    // NodeUpdate
    new NodeUpdate(
      makeUpdateId(0x01),
      makeEntityId(0x10),
      makeEntityId(0x20),
      {
        type: 'SubscriptionUpdate',
        items: [
          new SubscriptionUpdateItem(
            makeEntityId(0x30),
            makeCollectionId('users'),
            { type: 'EventOnly', events: [makeEventFragment()] },
            [[makeQueryId(1), { type: 'Initial' }]],
          ),
        ],
      },
    ).encode(writer);

    // SubscriptionUpdateItem (standalone)
    new SubscriptionUpdateItem(
      makeEntityId(0x40),
      makeCollectionId('posts'),
      { type: 'StateAndEvent', state: makeStateFragment(), events: [makeEventFragment()] },
      [
        [makeQueryId(2), { type: 'Add' }],
        [makeQueryId(3), { type: 'Remove' }],
      ],
    ).encode(writer);

    // EventOnly (standalone)
    encodeUpdateContent(writer, { type: 'EventOnly', events: [makeEventFragment()] });

    // StateAndEvent (standalone)
    encodeUpdateContent(writer, {
      type: 'StateAndEvent',
      state: makeStateFragment(),
      events: [makeEventFragment()],
    });

    // MembershipChange variants
    encodeMembershipChange(writer, { type: 'Initial' });
    encodeMembershipChange(writer, { type: 'Add' });
    encodeMembershipChange(writer, { type: 'Remove' });

    // NodeUpdateAck
    new NodeUpdateAck(
      makeUpdateId(0x02),
      makeEntityId(0x50),
      makeEntityId(0x60),
      { type: 'Success' },
    ).encode(writer);

    // NodeUpdateAckBody::Success (standalone)
    encodeNodeUpdateAckBody(writer, { type: 'Success' });

    // NodeUpdateAckBody::Error (standalone)
    encodeNodeUpdateAckBody(writer, { type: 'Error', message: 'update failed' });

    expectBytesEqual(writer.finish(), fixture, 'update.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// MESSAGE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('message.bin fixture', () => {
  test('decode: Presence message, PeerMessage, NodeMessage variants', () => {
    const data = loadFixture('message.bin');
    const reader = new BincodeReader(data);

    // Message::Presence
    const presenceMsg = decodeMessage(reader);
    expect(presenceMsg.type).toBe('Presence');
    if (presenceMsg.type === 'Presence') {
      expect(presenceMsg.presence.nodeId.bytes).toEqual(makeEntityId(0x01).bytes);
      expect(presenceMsg.presence.durable).toBe(true);
      expect(presenceMsg.presence.systemRoot).toBeNull();
    }

    // Message::PeerMessage(NodeMessage::Request)
    const peerRequest = decodeMessage(reader);
    expect(peerRequest.type).toBe('PeerMessage');
    if (peerRequest.type === 'PeerMessage') {
      expect(peerRequest.nodeMessage.type).toBe('Request');
      if (peerRequest.nodeMessage.type === 'Request') {
        expect(peerRequest.nodeMessage.auth.length).toBe(1);
        expect(peerRequest.nodeMessage.auth[0].data).toEqual(new Uint8Array([0xAA, 0xBB]));
        expect(peerRequest.nodeMessage.request.body.type).toBe('Get');
      }
    }

    // NodeMessage::Request (standalone)
    const nodeMsgRequest = decodeNodeMessage(reader);
    expect(nodeMsgRequest.type).toBe('Request');
    if (nodeMsgRequest.type === 'Request') {
      expect(nodeMsgRequest.auth.length).toBe(0);
      expect(nodeMsgRequest.request.id.toUlidString()).toBe(makeRequestId(0x50).toUlidString());
      if (nodeMsgRequest.request.body.type === 'Get') {
        expect(nodeMsgRequest.request.body.collection.value).toBe('items');
        expect(nodeMsgRequest.request.body.ids.length).toBe(0);
      }
    }

    // NodeMessage::Response (standalone)
    const nodeMsgResponse = decodeNodeMessage(reader);
    expect(nodeMsgResponse.type).toBe('Response');
    if (nodeMsgResponse.type === 'Response') {
      expect(nodeMsgResponse.response.requestId.toUlidString()).toBe(makeRequestId(0x80).toUlidString());
      expect(nodeMsgResponse.response.body.type).toBe('Success');
    }

    // NodeMessage::Update (standalone)
    const nodeMsgUpdate = decodeNodeMessage(reader);
    expect(nodeMsgUpdate.type).toBe('Update');
    if (nodeMsgUpdate.type === 'Update') {
      expect(nodeMsgUpdate.update.id.toUlidString()).toBe(makeUpdateId(0x01).toUlidString());
      expect(nodeMsgUpdate.update.body.type).toBe('SubscriptionUpdate');
      if (nodeMsgUpdate.update.body.type === 'SubscriptionUpdate') {
        expect(nodeMsgUpdate.update.body.items.length).toBe(0);
      }
    }

    // NodeMessage::UpdateAck (standalone)
    const nodeMsgUpdateAck = decodeNodeMessage(reader);
    expect(nodeMsgUpdateAck.type).toBe('UpdateAck');
    if (nodeMsgUpdateAck.type === 'UpdateAck') {
      expect(nodeMsgUpdateAck.updateAck.id.toUlidString()).toBe(makeUpdateId(0x02).toUlidString());
      expect(nodeMsgUpdateAck.updateAck.body.type).toBe('Success');
    }

    // NodeMessage::UnsubscribeQuery (standalone)
    const nodeMsgUnsub = decodeNodeMessage(reader);
    expect(nodeMsgUnsub.type).toBe('UnsubscribeQuery');
    if (nodeMsgUnsub.type === 'UnsubscribeQuery') {
      expect(nodeMsgUnsub.from.bytes).toEqual(makeEntityId(0xF0).bytes);
      expect(nodeMsgUnsub.queryId.toUlidString()).toBe(makeQueryId(77).toUlidString());
    }

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('message.bin');
    const writer = new BincodeWriter();

    // Message::Presence
    encodeMessage(writer, {
      type: 'Presence',
      presence: new Presence(makeEntityId(0x01), true, null),
    });

    // Message::PeerMessage(NodeMessage::Request with auth)
    encodeMessage(writer, {
      type: 'PeerMessage',
      nodeMessage: {
        type: 'Request',
        auth: [new AuthData(new Uint8Array([0xAA, 0xBB]))],
        request: new NodeRequest(
          makeRequestId(0x10),
          makeEntityId(0x20),
          makeEntityId(0x30),
          { type: 'Get', collection: makeCollectionId('users'), ids: [makeEntityId(0x40)] },
        ),
      },
    });

    // NodeMessage::Request (standalone, empty auth)
    encodeNodeMessage(writer, {
      type: 'Request',
      auth: [],
      request: new NodeRequest(
        makeRequestId(0x50),
        makeEntityId(0x60),
        makeEntityId(0x70),
        { type: 'Get', collection: makeCollectionId('items'), ids: [] },
      ),
    });

    // NodeMessage::Response (standalone)
    encodeNodeMessage(writer, {
      type: 'Response',
      response: new NodeResponse(
        makeRequestId(0x80),
        makeEntityId(0x90),
        makeEntityId(0xA0),
        { type: 'Success' },
      ),
    });

    // NodeMessage::Update (standalone)
    encodeNodeMessage(writer, {
      type: 'Update',
      update: new NodeUpdate(
        makeUpdateId(0x01),
        makeEntityId(0xB0),
        makeEntityId(0xC0),
        { type: 'SubscriptionUpdate', items: [] },
      ),
    });

    // NodeMessage::UpdateAck (standalone)
    encodeNodeMessage(writer, {
      type: 'UpdateAck',
      updateAck: new NodeUpdateAck(
        makeUpdateId(0x02),
        makeEntityId(0xD0),
        makeEntityId(0xE0),
        { type: 'Success' },
      ),
    });

    // NodeMessage::UnsubscribeQuery (standalone)
    encodeNodeMessage(writer, {
      type: 'UnsubscribeQuery',
      from: makeEntityId(0xF0),
      queryId: makeQueryId(77),
    });

    expectBytesEqual(writer.finish(), fixture, 'message.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// PRESENCE FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('presence.bin fixture', () => {
  test('decode: durable/no root, ephemeral/with root', () => {
    const data = loadFixture('presence.bin');
    const reader = new BincodeReader(data);

    // Presence: durable, no system_root
    const presenceDurable = Presence.decode(reader);
    expect(presenceDurable.nodeId.bytes).toEqual(makeEntityId(0x01).bytes);
    expect(presenceDurable.durable).toBe(true);
    expect(presenceDurable.systemRoot).toBeNull();

    // Presence: ephemeral, with system_root
    const presenceEphemeral = Presence.decode(reader);
    expect(presenceEphemeral.nodeId.bytes).toEqual(makeEntityId(0x02).bytes);
    expect(presenceEphemeral.durable).toBe(false);
    expect(presenceEphemeral.systemRoot).not.toBeNull();
    expect(presenceEphemeral.systemRoot!.payload.entityId.bytes).toEqual(makeEntityId(0x00).bytes);
    expect(presenceEphemeral.systemRoot!.payload.collection.value).toBe('test_collection');
    expect(presenceEphemeral.systemRoot!.attestations.length).toBe(2);

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('presence.bin');
    const writer = new BincodeWriter();

    new Presence(makeEntityId(0x01), true, null).encode(writer);

    new Presence(
      makeEntityId(0x02),
      false,
      new Attested(makeEntityState(), makeAttestationSetTwo()),
    ).encode(writer);

    expectBytesEqual(writer.finish(), fixture, 'presence.bin');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// SYSTEM FIXTURE
// ═══════════════════════════════════════════════════════════════════════════════

describe('system.bin fixture', () => {
  test('decode: SysRoot and Collection items', () => {
    const data = loadFixture('system.bin');
    const reader = new BincodeReader(data);

    const sysRoot = decodeItem(reader);
    expect(sysRoot.type).toBe('SysRoot');

    const collectionItem = decodeItem(reader);
    expect(collectionItem.type).toBe('Collection');
    if (collectionItem.type === 'Collection') {
      expect(collectionItem.name).toBe('users');
    }

    expect(reader.remaining).toBe(0);
  });

  test('round-trip: encode matches fixture bytes', () => {
    const fixture = loadFixture('system.bin');
    const writer = new BincodeWriter();

    encodeItem(writer, { type: 'SysRoot' });
    encodeItem(writer, { type: 'Collection', name: 'users' });

    expectBytesEqual(writer.finish(), fixture, 'system.bin');
  });
});
